09-24-2025-11:30:02

diff --git a/LOCAL/yts/yts b/LOCAL/yts/yts
--- a/LOCAL/yts/yts
+++ b/LOCAL/yts/yts
@@ -20,6 +20,7 @@ WHITE_ON_GREY="\033[0m\033[0;1;37;100m"
 # Imports
 [[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
 source ${_LIB_DIR}/LIB_INIT.zsh
+source ${_LIB_DIR}/VALIDATE.zsh
 source ${_LIB_DIR}/PATH.zsh
 source ${_LIB_DIR}/DATE.zsh
 source ${_LIB_DIR}/UTILS.zsh
@@ -82,7 +83,9 @@ _YTS_URL_LOG=/tmp/yts.url.log
 g_DISPLAY_KEY=''
 g_IND_FLIP=false
 g_LAST_CODE_UPD=?
-g_LTYPE=y
+g_LAST_SPEED=0
+g_LAST_STYPE=0
+g_LAST_FAV_TYPE=y
 g_MASK_NDX=1
 g_PID=?
 g_PREFER_LIVE=''
@@ -134,10 +137,11 @@ action_do () {
 	local RC1=0
 	local RC2=0
 	local SCAN_LIMIT=0
+	local SPEED=0
 	local TITLE=''
 	local URL=''
 	local WAIT=0
-	local L M S 
+	local L M S X
 
 	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
 
@@ -304,8 +308,8 @@ action_do () {
 			elif grep -qi 'error' <<<${LOG_LINE} 2>/dev/null;then
 				logit ${_YTS_DBG_LOG} "${0}: GOT ERROR:${LOG_LINE}"
 				ERR=${LOG_LINE}
-			elif grep -qi 'Fixing MPEG-TS' <<<${LOG_LINE} 2>/dev/null;then
-				logit ${_YTS_DBG_LOG} "${0}: GOT Fragmented completion:${LOG_LINE}"
+			elif grep -qi 'Fixing MPEG-TS\|FixupM3u8' <<<${LOG_LINE} 2>/dev/null;then
+				logit ${_YTS_DBG_LOG} "${0}: GOT Fragmention post-process:${LOG_LINE}"
 				ETA="100% of download completed"
 			elif grep -qi '100%' <<<${LOG_LINE} 2>/dev/null;then
 				logit ${_YTS_DBG_LOG} "${0}: GOT completion:${LOG_LINE}"
@@ -340,7 +344,8 @@ action_do () {
 			LINE_COLOR=''
 			if [[ -n ${ETA} && ${ETA_COMPLETE} == 'false' ]];then
 				ERROR_CNT=0 
-				download_indicator ${ETA}
+				SPEED=$(get_speed ${ETA})
+				download_indicator ${SPEED}
 				case ${ETA:l} in
 					*100*%*) LINE_COLOR='<B><g>';ETA_COMPLETE=true;; # Stop parsing ETA
 					*mib/s*) LINE_COLOR='<w>';;
@@ -415,14 +420,6 @@ box_center () {
 	echo $(center -y${BOX} -t${BOX_WIDTH} ${TXT})
 }
 
-clean_author () {
-	local AUTHOR=${1}
-
-	[[ ${AUTHOR} =~ '[?]' ]] && AUTHOR=$(sed 's/[?].*//' <<< ${AUTHOR})
-
-	echo ${AUTHOR}
-}
-
 clean_title () {
 	local TITLE=${1}
 	local TITLE_LEN=${2:=${_MAX_TITLE}}
@@ -433,13 +430,11 @@ clean_title () {
 	local UCASE_LIMIT=4
 	local W U
 
-	logit ${_YTS_DBG_LOG} "${0}: TITLE:${TITLE}"
 
 	STR=$(html2text -width ${_MAX_COLS} -ascii <<<${TITLE}) # Convert any HTML 
-	#[[ ${TITLE} != ${STR} ]] && logit ${_YTS_DBG_LOG} "${0}: HTML -> ascii:${STR}"
 
 	STR=$(str_word_clip ${STR} ${TITLE_LEN})
-	#logit ${_YTS_DBG_LOG} "${0}: str_word_clip TITLE:${TITLE}"
+	logit ${_YTS_DBG_LOG} "${0}: str_word_clip -  TITLE LEN:${#TITLE}, RETURN LEN:${#STR}"
 
 	TITLE=${STR}
 	STR=$(tr '\n' ' ' <<<${STR}) # html2text can insert a newline if STR exceeds --width
@@ -516,7 +511,8 @@ dashed_line () {
 }
 
 download_indicator () {
-	local LINE=${@}
+	local SPEED=$(cut -d'|' -f1 <<<${1})
+	local STYPE=$(cut -d'|' -f2 <<<${1})
 	local L_OBJ="\\u23FA"
 	local M_OBJ="\\u25CF"
 	local R_OBJ="\\u2B24"
@@ -525,18 +521,44 @@ download_indicator () {
 	local -A OBJS_2=(1 ${R_OBJ} 2 ${M_OBJ} 3 ${L_OBJ})
 	local BORDER_COLOR=''
 	local DELAY=.3
+	local IND_X=$(( _ALERT_COORDS[X] + 1 ))
+	local IND_Y=$(( _ALERT_COORDS[Y] + 7 ))
 	local L_SIDE="\\u2770"
 	local R_SIDE="\\u2771"
 	local MASK=""
-	local IND_X=$(( _ALERT_COORDS[X] + 1 ))
-	local IND_Y=$(( _ALERT_COORDS[Y] + 7 ))
 	local OBJ_COLOR="${BOLD}${GREEN_FG}"
+	local SP_DIR=I
 
-	case ${LINE:l} in
-		*mib*) BORDER_COLOR="${BOLD}${MAGENTA_FG}";;
-		*kib*) BORDER_COLOR="${BOLD}${RED_FG}";;
-	esac
-	
+	[[ -z ${SPEED} ]] && SPEED=0
+	[[ -z ${g_LAST_SPEED} ]] && g_LAST_SPEED=0
+	[[ -z ${STYPE} ]] && STYPE=''
+	[[ -z ${g_LAST_STYPE} ]] && g_LAST_STYPE=''
+
+	if [[ ${SPEED} -gt ${g_LAST_SPEED} ]];then 
+		OBJ_COLOR="${BOLD}${GREEN_FG}"
+		SP_DIR=I # Increasing
+	elif [[ ${SPEED} -lt ${g_LAST_SPEED} ]];then 
+		OBJ_COLOR="${BOLD}${YELLOW_FG}"
+		SP_DIR=D # Decreasing
+	else
+		OBJ_COLOR="${BOLD}${WHITE_FG}"
+		SP_DIR=I # Stable
+	fi
+
+	if [[ ${STYPE} == 'M' && ${g_LAST_STYPE} == 'K' ]];then 
+		OBJ_COLOR="${BOLD}${GREEN_FG}"
+		SP_DIR=I # Increasing
+	elif [[ ${STYPE} == 'K' && ${g_LAST_STYPE} == 'M' ]];then 
+		OBJ_COLOR="${BOLD}${YELLOW_FG}"
+		SP_DIR=D # Decreasing
+	fi
+
+	if [[ ${SP_DIR} == 'I' ]];then 
+		BORDER_COLOR="${BOLD}${MAGENTA_FG}"
+	elif [[ ${SP_DIR} == 'D' ]];then 
+		BORDER_COLOR="${BOLD}${RED_FG}"
+	fi
+
 	OBJS=(${(kv)OBJS_1}) # Init
 
 	if [[ ${g_IND_FLIP} == 'true' ]];then
@@ -557,6 +579,9 @@ download_indicator () {
 	[[ ${g_MASK_NDX} -gt 3 ]] && g_MASK_NDX=1
 
  	tcup ${IND_X} ${IND_Y} && echo -n "${MASK}" && sleep ${DELAY}
+
+	g_LAST_SPEED=${SPEED}
+	g_LAST_STYPE=${STYPE}
 }
 
 download_select () {
@@ -693,20 +718,20 @@ fav_get () {
 			D_KEY=${L:gs/_/ /}
 			Q_KEY=$(cut -d: -f1 <<<${_FAV_LIST[${L}]})
 			Q_OPT=$(cut -d: -f2 <<<${_FAV_LIST[${L}]:l})
-			if [[ ${g_LTYPE} == 'c' && ${Q_OPT[1]} == 'p' ]];then # (Future: change favorite code to 'c')
+			if [[ ${g_LAST_FAV_TYPE} == 'c' && ${Q_OPT[1]} == 'p' ]];then # (Future: change favorite code to 'c')
 				LIST+=${D_KEY}
 				QUERY_KEYS[${D_KEY}]=${Q_KEY}
 				QUERY_OPTS[${D_KEY}]=${Q_OPT}
 				O_COLOR=${RED_FG}
 				C_MSG=" <I>(Custom List)<N> "
-			elif [[ ${g_LTYPE} == 'y' && ${Q_OPT[1]} == 'y' ]];then
+			elif [[ ${g_LAST_FAV_TYPE} == 'y' && ${Q_OPT[1]} == 'y' ]];then
 				LIST+=${D_KEY}
 				QUERY_KEYS[${D_KEY}]=${Q_KEY}
 				QUERY_OPTS[${D_KEY}]=${Q_OPT}
 				ENGINE=youtube
 				O_COLOR=${CYAN_FG}
 				C_MSG=''
-			elif [[ ${g_LTYPE} == 'r' && ${Q_OPT[1]} == 'r' ]];then
+			elif [[ ${g_LAST_FAV_TYPE} == 'r' && ${Q_OPT[1]} == 'r' ]];then
 				LIST+=${D_KEY}
 				QUERY_KEYS[${D_KEY}]=${Q_KEY}
 				QUERY_OPTS[${D_KEY}]=${Q_OPT}
@@ -733,7 +758,7 @@ fav_get () {
 		msg_line_weight light
 
 		[[ ${_SEL_KEY} == 'd' ]] && fav_delete ${_SEL_VAL}
-		[[ ${_SEL_KEY} =~ 'y|r|c' ]] && g_LTYPE=${_SEL_KEY}
+		[[ ${_SEL_KEY} =~ 'y|r|c' ]] && g_LAST_FAV_TYPE=${_SEL_KEY}
 
 		if [[ ${_SEL_KEY} == '?' ]];then
 			g_QRY_ENGINE=${ENGINE}
@@ -882,21 +907,30 @@ get_field () {
 	fi
 
 	if [[ ${FIELD} == 'author' ]];then
-		if [[ ${g_SEARCH_TYPE} == 'general' ]];then
- 			TSTR=${(C)STR}
-		else
-			[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}: Author:${STR} swapped with g_DISPLAY_KEY:${g_DISPLAY_KEY}"
-			TSTR=${g_DISPLAY_KEY:gs/_/ /}
-		fi
-		STR=${TSTR:=${STR}}
+		STR=${g_DISPLAY_KEY:gs/_/ /}
 	fi
-
-	#logit ${_YTS_DBG_LOG} "${0}: FIELD:${FIELD} STR:${STR}"
 
 	if [[ -n ${_FIELD_LEN[${FIELD}]} ]];then
 		echo -n ${STR[1,${_FIELD_LEN[${FIELD}]}]}
 	else
 		echo -n ${STR}
+	fi
+}
+
+get_speed () {
+	local SPEED=${@}
+	local TYPE=''
+
+	SPEED=$(sed -E 's/^.*at\s+//' <<<${SPEED:l} | cut -d' ' -f1 | sed 's/[/]s//')
+	[[ ${SPEED} =~ 'mib' ]] && TYPE=M || TYPE=K
+	SPEED=$(sed 's/.ib//' <<<${SPEED})
+
+	[[ ${SPEED} == '100%' ]] && SPEED=0 # Completed
+
+	if validate_is_number ${SPEED};then
+		echo "${SPEED}|${TYPE}"
+	else
+		echo "0|${TYPE}"
 	fi
 }
 
@@ -994,7 +1028,7 @@ last_code_update () {
 	fi
 }
 
-last_file () {
+last_file_downloaded () {
 	local ST=''
 	local FN=''
 	local IN=''
@@ -1023,7 +1057,7 @@ list_reset () {
 
 log_add () {
 	local NDX=${1}
-	local LF=$(last_file) # Filename|Inode
+	local LF=$(last_file_downloaded) # Filename|Inode
 	local FN=$(cut -d'|' -f1 <<<${LF}) # Filename
 	local IN=$(cut -d'|' -f2 <<<${LF}) # Inode
 	local TL=$(get_field title ${NDX}) # Title
@@ -1219,27 +1253,11 @@ post_process () {
 		[[ ${?} -eq 0 ]] && logit ${_YTS_DBG_LOG} "${0}: deleted ${F}"
 	done
 
-	LF=$(last_file) # Filename and Inode
+	LF=$(last_file_downloaded) # Filename and Inode
 	FN=$(cut -d'|' -f1 <<<${LF}) # Filename
 	logit ${_YTS_DBG_LOG} "${0}: Last FN:${FN}"
 
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: FN:${FN:t}"
-
-	NEW_FN=$(clean_title ${FN:t:r:gs/_/ /} ${_MAX_FLEN}) # Clean tail, no extension, no underscores
-	NEW_FN=${NEW_FN[1,${_MAX_FLEN}]} # Filename length
-	NEW_FN=$(perl -pe 's/\.$//g' <<<${NEW_FN}) # Kill any trailing dots
-
-	NEW_FN="$(str_trim ${FN:h}/${NEW_FN}).${FN:e}" # Add path and extension
-	logit ${_YTS_DBG_LOG} "${0}: Formatted:${NEW_FN}"
-
-	if [[ ${FN} != ${NEW_FN} ]];then
-		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: Saving changes:${FN:t} -> ${NEW_FN:t}"
-		logit ${_YTS_DBG_LOG} "${0}: Overwriting:${FN}"
-		mv -f "${FN}" "${NEW_FN}" 2>> ${_ERROR_LOG} # Write any changes
-		[[ ${?} -ne 0 ]] && echo "${0}: Move failed ${FN} to ${NEW_FN}" >> ${_ERROR_LOG}
-	fi
-
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: Cleaned:${FN:t}"
+	set_final_fn ${FN}
 }
 
 query_rumble () {
@@ -1280,7 +1298,7 @@ query_rumble () {
 	g_SEARCH_TYPE=channel
 	#Sort tag 
 	#&sort=date&section=sort 
-
+	 
 	if [[ ${g_PREFER_LIVE} == 'true' ]];then
 		msg_box -c "Requesting <c><I>livestream channel<N> search..."
 
@@ -1355,7 +1373,7 @@ query_rumble () {
 			g_SEARCH_TYPE=general
 
 			GEN_SEARCH=$(sed 's/ /%20/g' <<<${g_QUERY_KEY})
-			QRY="https://rumble.com/search/all?q=${GEN_SEARCH}"
+			QRY="https://rumble.com/search/all?q=${GEN_SEARCH}&sort=date&section=sort"
 			logit ${_YTS_URL_LOG} "${0}:${QRY}"
 			PG=$(wget -q -O - ${QRY})
 			if [[ ${_DEBUG} -ge ${_HIGH_DBG} ]];then
@@ -1397,11 +1415,15 @@ query_rumble () {
 
 	for V in ${_LOCAL_LIST};do
 		AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${V})
-		AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${V}) AUTHOR=$(clean_author ${AUTHOR})
+		AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${V})
 		TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${V}); TITLE=$(clean_title ${TITLE})
 		URL=$(cut -d'|' -f${FIELD_MAP[url]} <<<${V}); URL="http://rumble.com${URL}"
 		TIME=$(cut -d'|' -f${FIELD_MAP[time]} <<<${V})
 		AGETIME=$(cut -d'|' -f${FIELD_MAP[agetime]} <<<${V});	AGETIME="(${AGETIME:s/|/ /})"
+
+		[[ -z ${AGE} ]] && continue
+		[[ ${TIME:l} == 'live' ]] && continue
+		[[ ! ${TIME:l} =~ ':' ]] && continue
 
 		WORK_LIST+="${AGE}|${AUTHOR}|${TITLE}|${URL}|${TIME}|${AGETIME}"
 	done
@@ -1434,77 +1456,77 @@ query_youtube () {
 	if [[ ${g_STRICT} == 'true' ]];then # Strict requested
 		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}STRICT FILTER ACTIVE${RESET}"
 		g_PROXY_CMD="node ${_JS_SCRIPT} -s ${(qqq)g_QUERY_KEY}"
-	else
-		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}STRICT FILTER INACTIVE${RESET}"
-		g_PROXY_CMD="node ${_JS_SCRIPT} -a recent ${(qqq)g_QUERY_KEY}"
-	fi
-
-	if [[ ${_DEBUG} -ge ${_LOW_DBG} ]];then
-		dbg "${0}:${LINENO} ${CYAN_FG}g_QUERY_KEY${RESET}:${g_QUERY_KEY}, {CYAN_FG}g_PROXY_CMD${RESET}:${g_PROXY_CMD}"
-	fi
-
-	logit ${_YTS_DBG_LOG} "${0}:g_QUERY_KEY:${g_QUERY_KEY}, g_PROXY_CMD:${g_PROXY_CMD}"
-
-	_LOCAL_LIST=()
-
-	g_SEARCH_TYPE='general'
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}GENERAL SEARCH${RESET}"
-
-	NDX=0
-	while read LINE;do
-		[[ ${LINE:l} =~ 'matched' ]] && DATA=true && continue
-
-		[[ ${LINE:l} =~ 'usage' && ${DATA} != 'true' ]] && exit_leave
-		[[ ${LINE:l} =~ 'error' && ${DATA} != 'true' ]] && exit_leave $(err_msg_exit E "${PROXY_CMD} returned an error")
-
-		((NDX++))
-		[[ ${LINE:l} =~ 'rejected' ]] && _REJECTS[${NDX}]=true || _REJECTS[${NDX}]=false
-
-		STR=$(str_to_ascii <<<${LINE}) # Scrub non ascii
-		STR=${STR:s/Streamed //}
-
-		if [[ ${g_STRICT} == 'false' ]];then # Apply filtering to non strict results
-			HIT=false
-			AUTHOR=$(cut -d'|' -f2 <<<${LINE}) && AUTHOR=$(str_to_ascii ${AUTHOR})
-			TITLE=$(cut -d'|' -f3 <<<${LINE}) && TITLE=$(str_to_ascii ${TITLE})
-			[[ ${TITLE:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:gs/ //:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
-			if [[ ${_DEBUG} -ge ${_MID_DBG} ]];then
-				dbg "${0}:${LINENO} NON STRICT FILTERING, AUTHOR:${AUTHOR}, g_DISPLAY_KEY:${g_DISPLAY_KEY}, g_QUERY_KEY:${g_QUERY_KEY}, HIT:${HIT}"
-			fi
-			[[ ${HIT} == 'false' ]] && continue
-		fi
-		 
-		[[ ${_REJECTS[${NDX}]} == 'false' && ${DATA} == 'true' ]] && _LOCAL_LIST+=${STR}
-	done< <(eval ${g_PROXY_CMD})
-
-	[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="$(total_rejects ${NDX})" || g_STRICT_MSG=''
-
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
-	[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST content:\n $(for L in ${_LOCAL_LIST};do echo ${L};done)"
-
-	[[ ${_SMCUP} == 'false' ]] && do_smcup
-
-	# Search failed
-	if ! arr_is_populated "${_LOCAL_LIST}";then
-		g_PROXY_CMD=$(str_trim ${(Q)g_PROXY_CMD})
-		if [[ ${g_STRICT} == 'true' ]];then
-			msg_box -H2 -p -PK "<r>Query returned no rows<N>|<I>Strict filter is active<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
 		else
-			msg_box -H2 -p -PK "<r>Query returned no rows<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
+			[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}STRICT FILTER INACTIVE${RESET}"
+			g_PROXY_CMD="node ${_JS_SCRIPT} -a recent ${(qqq)g_QUERY_KEY}"
 		fi
-		return 1
-	fi
 
-	for F in ${_LOCAL_LIST};do
-		AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${F})
-		AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${F})
-		TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${F}); TITLE=$(clean_title ${TITLE})
-		if [[ ${AUTHOR} == 'blancolirio' ]];then # Weird problem workaraound - spanish titles on blancolirio
-			if perl -wln -e "if (/\b.*[ae]ntes\b|\bll.*\b|\bel\b|\bya\b|\by\b|\bla\b|\bal\b|\bde\b|\bdel\b|\bque\b/) { exit 0 } else { exit 1 }" <<<${TITLE:l};then
-				TITLE=$(echo ${TITLE} | trans -brief -no-pager -no-ansi -no-theme es:en)
+		if [[ ${_DEBUG} -ge ${_LOW_DBG} ]];then
+			dbg "${0}:${LINENO} ${CYAN_FG}g_QUERY_KEY${RESET}:${g_QUERY_KEY}, {CYAN_FG}g_PROXY_CMD${RESET}:${g_PROXY_CMD}"
+		fi
+
+		logit ${_YTS_DBG_LOG} "${0}:g_QUERY_KEY:${g_QUERY_KEY}, g_PROXY_CMD:${g_PROXY_CMD}"
+
+		_LOCAL_LIST=()
+
+		g_SEARCH_TYPE='general'
+		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}GENERAL SEARCH${RESET}"
+
+		NDX=0
+		while read LINE;do
+			[[ ${LINE:l} =~ 'matched' ]] && DATA=true && continue
+
+			[[ ${LINE:l} =~ 'usage' && ${DATA} != 'true' ]] && exit_leave
+			[[ ${LINE:l} =~ 'error' && ${DATA} != 'true' ]] && exit_leave $(err_msg_exit E "${PROXY_CMD} returned an error")
+
+			((NDX++))
+			[[ ${LINE:l} =~ 'rejected' ]] && _REJECTS[${NDX}]=true || _REJECTS[${NDX}]=false
+
+			STR=$(str_to_ascii <<<${LINE}) # Scrub non ascii
+			STR=${STR:s/Streamed //}
+
+			if [[ ${g_STRICT} == 'false' ]];then # Apply filtering to non strict results
+				HIT=false
+				AUTHOR=$(cut -d'|' -f2 <<<${LINE}) && AUTHOR=$(str_to_ascii ${AUTHOR})
+				TITLE=$(cut -d'|' -f3 <<<${LINE}) && TITLE=$(str_to_ascii ${TITLE})
+				[[ ${TITLE:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
+				[[ ${AUTHOR:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
+				[[ ${AUTHOR:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
+				[[ ${AUTHOR:gs/ //:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
+				if [[ ${_DEBUG} -ge ${_MID_DBG} ]];then
+					dbg "${0}:${LINENO} NON STRICT FILTERING, AUTHOR:${AUTHOR}, g_DISPLAY_KEY:${g_DISPLAY_KEY}, g_QUERY_KEY:${g_QUERY_KEY}, HIT:${HIT}"
+				fi
+				[[ ${HIT} == 'false' ]] && continue
+			fi
+			 
+			[[ ${_REJECTS[${NDX}]} == 'false' && ${DATA} == 'true' ]] && _LOCAL_LIST+=${STR}
+		done< <(eval ${g_PROXY_CMD})
+
+		[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="$(total_rejects ${NDX})" || g_STRICT_MSG=''
+
+		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
+		[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST content:\n $(for L in ${_LOCAL_LIST};do echo ${L};done)"
+
+		[[ ${_SMCUP} == 'false' ]] && do_smcup
+
+		# Search failed
+		if ! arr_is_populated "${_LOCAL_LIST}";then
+			g_PROXY_CMD=$(str_trim ${(Q)g_PROXY_CMD})
+			if [[ ${g_STRICT} == 'true' ]];then
+				msg_box -H2 -p -PK "<r>Query returned no rows<N>|<I>Strict filter is active<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
+			else
+				msg_box -H2 -p -PK "<r>Query returned no rows<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
+			fi
+			return 1
+		fi
+
+		for F in ${_LOCAL_LIST};do
+			AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${F})
+			AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${F})
+			TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${F}); TITLE=$(clean_title ${TITLE})
+			if [[ ${AUTHOR} == 'blancolirio' ]];then # Weird problem workaraound - spanish titles on blancolirio
+				if perl -wln -e "if (/\b.*[ae]ntes\b|\bll.*\b|\bel\b|\bya\b|\by\b|\bla\b|\bal\b|\bde\b|\bdel\b|\bque\b|\bpara\b|\bpor\b/) { exit 0 } else { exit 1 }" <<<${TITLE:l};then
+					TITLE=$(echo ${TITLE} | trans -brief -no-pager -no-ansi -no-theme es:en)
 			fi
 		fi
 		URL=$(cut -d'|' -f${FIELD_MAP[url]} <<<${F})
@@ -1516,6 +1538,29 @@ query_youtube () {
 	_LOCAL_LIST=(${WORK_LIST})
 
 	return 0
+}
+
+set_final_fn () {
+	local FN=${1}
+	local NEW_FN=''
+
+	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: FN:${FN:t}"
+
+	NEW_FN=$(clean_title ${FN:t:r:gs/_/ /} ${_MAX_FLEN}) # Clean tail, no extension, no underscores
+	NEW_FN=${NEW_FN[1,${_MAX_FLEN}]} # Filename length
+	NEW_FN=$(perl -pe 's/\.$//g' <<<${NEW_FN}) # Kill any trailing dots
+
+	NEW_FN="$(str_trim ${FN:h}/${NEW_FN}).${FN:e}" # Add path and extension
+	logit ${_YTS_DBG_LOG} "${0}: Formatted:${NEW_FN}"
+
+	if [[ ${FN} != ${NEW_FN} ]];then
+		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: Saving changes:${FN:t} -> ${NEW_FN:t}"
+		logit ${_YTS_DBG_LOG} "${0}: Overwriting:${FN}"
+		mv -f "${FN}" "${NEW_FN}" 2>> ${_ERROR_LOG} # Write any changes
+		[[ ${?} -ne 0 ]] && echo "${0}: Move failed ${FN} to ${NEW_FN}" >> ${_ERROR_LOG}
+	fi
+
+	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: Cleaned:${FN:t}"
 }
 
 set_item_color () {
diff --git a/ZSH_LIB_UTILS/win_max b/ZSH_LIB_UTILS/win_max
--- a/ZSH_LIB_UTILS/win_max
+++ b/ZSH_LIB_UTILS/win_max
@@ -6,30 +6,323 @@ source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
 source ${_LIB_DIR}/UTILS.zsh
 source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last
 
+# Declarations
+typeset -A _APP_TAGS=(brave-browser brave com.obsproject.studio obs firefox_firefox firefox haruna_haruna haruna)
+typeset -A _FLD_LIST=(WID 1 DID 2 PID 3 CLIENT 4 TITLE 5 MAX 6)
+typeset -a _CUR_WIN=()
+typeset -aU _WIN_LIST=()
+
+# Vars
+_QUICK=false
+
 # Constants
 _SCRIPT=${0:t}
 _LOG=/tmp/${_SCRIPT}.log
 
-# Execution
+# Functions
+get_app_tag () {
+	local APP=${1:l} # Lowercase
+	local APP_TAG=''
+
+	# Handle any alternate tags
+	if [[ -n ${_APP_TAGS[${APP}]} ]];then
+		APP_TAG=${_APP_TAGS[${APP}]}
+		logit ${_LOG} "${0}: APP:${APP} using APP_TAG:${APP_TAG}"
+	else
+		APP_TAG=${APP}
+	fi
+
+	echo ${APP_TAG}
+}
+
+get_id_title () {
+	local TITLE_ARG=${1}
+	local TITLE=''
+	local WID=''
+	local W
+
+	if [[ ${TITLE_ARG} == 'terminal' ]];then # Special handling of terminal to get most recent
+		WID=$(get_last_term)
+		logit ${_LOG} "${0}: Terminal has WID:${WID}"
+	else
+		for W in ${_WIN_LIST};do
+			WID=$(cut -d'|' -f${_FLD_LIST[WID]} <<<${W})
+			TITLE=$(cut -d'|' -f${_FLD_LIST[TITLE]} <<<${W})
+			if [[ ${TITLE:l} =~ ${TITLE_ARG:l} ]];then
+				logit ${_LOG} "${0}: TITLE:${TITLE} has WID:${WID}"
+				break
+			else
+				WID=''
+			fi
+		done
+	fi
+
+	echo ${WID}
+}
+
+get_id_pid () {
+	local PID_ARG=${1}
+	local PID=''
+	local TITLE=''
+	local WID=''
+	local W
+
+	for W in ${_WIN_LIST};do
+		WID=$(cut -d'|' -f${_FLD_LIST[WID]} <<<${W})
+		PID=$(cut -d'|' -f${_FLD_LIST[PID]} <<<${W})
+		TITLE=$(cut -d'|' -f${_FLD_LIST[TITLE]} <<<${W})
+		if [[ ${PID_ARG} =~ ${PID} ]];then
+			logit ${_LOG} "${0}: PID:${PID} has WID:${WID}, TITLE:${TITLE}"
+			break
+		fi
+	done
+
+	echo ${WID}
+}
+
+get_id_wid () {
+	local WID_ARG=${1}
+	local TITLE=''
+	local WID=''
+	local W
+
+	for W in ${_WIN_LIST};do
+		WID=$(cut -d'|' -f${_FLD_LIST[WID]} <<<${W})
+		TITLE=$(cut -d'|' -f${_FLD_LIST[TITLE]} <<<${W})
+		if [[ ${WID_ARG} =~ ${WID} ]];then
+			logit ${_LOG} "${0}: WID:${WID} has TITLE:${TITLE}"
+			break
+		fi
+	done
+
+	echo ${WID}
+}
+
+get_win_id () {
+	local ARG=${1}
+	local TYPE=${2}
+	local WID=''
+
+	logit ${_LOG} "${0}: Obtaining WID for ARG:${ARG}"
+
+	case ${TYPE} in
+		TITLE) WID=$(get_id_title $(get_app_tag ${ARG}));;
+		PID) WID=$(get_id_pid ${ARG});;
+		WID) WID=$(get_id_wid ${ARG});;
+	esac
+
+	echo ${WID}
+}
+
+get_last_term () {
+	wmctrl -l | grep -i terminal | sort -r | head -1 | tr -s '[:space:]' | cut -d' ' -f1
+}
+
+is_maximized () {
+	local WID_ARG=${1}
+	local MAX=''
+	local WID=''
+	local W
+
+	for W in ${_WIN_LIST};do
+		WID=$(cut -d'|' -f${_FLD_LIST[WID]} <<<${W})
+		MAX=$(cut -d'|' -f${_FLD_LIST[MAX]} <<<${W})
+		if [[ ${WID_ARG} =~ ${WID} ]];then
+			logit ${_LOG} "${0}: WID:${WID} maximized:${MAX}"
+			break
+		fi
+	done
+
+	echo ${MAX} # returns true or false
+}
+
+set_cur_win () {
+	local EXPECT=${1}
+	local F1 F2 F3 F4 F5 MAX
+	local RETRIES=5
+	local TERMS=$(terms -c)
+	local TERM_CNT=0
+	local TRIES=0
+	local L
+
+	logit ${_LOG} "${0}: Expecting window:${EXPECT}"
+
+	[[ ${_QUICK} == 'true' ]] && RETRIES=2
+
+	while true;do
+		((TRIES++))
+		if [[ ${TRIES} -gt ${RETRIES} ]];then
+			logit ${_LOG} "${0}: Reached maximum retries:${RETRIES}"
+			break
+		fi
+
+		_CUR_WIN=("${(f)$(wmctrl -lp | tr -s '[:space:]')}")
+
+		for L in ${_CUR_WIN};do
+			F1=$(cut -d' ' -f${_FLD_LIST[WID]} <<<${L})
+			F2=$(cut -d' ' -f${_FLD_LIST[DID]} <<<${L})
+			F3=$(cut -d' ' -f${_FLD_LIST[PID]} <<<${L})
+			F4=$(cut -d' ' -f${_FLD_LIST[CLIENT]} <<<${L})
+			F5=$(cut -d' ' -f${_FLD_LIST[TITLE]}- <<<${L})
+
+			[[ ${F2} == '-1' ]] && continue # Eliminate invisible
+			[[ ${F5:l} =~ "terminal" ]] && ((TERM_CNT++)) # Count terminal hits
+
+			xwininfo -wm -id ${F1} 2>/dev/null | grep -qi 'maximized'
+			[[ ${?} -eq 0 ]] && MAX=true || MAX=false
+
+			_WIN_LIST+="${F1}|${F2}|${F3}|${F4}|${F5}|${MAX}"
+
+			if [[ -n ${EXPECT} && ${F5:l} =~ ${EXPECT} ]];then # Hit expected window
+				[[ ${EXPECT} =~ 'terminal' && ${TERM_CNT} -ne ${TERMS} ]] && continue
+				logit ${_LOG} "${0}: Got expected window:${EXPECT}, wmctrl:${F5}"
+				break 2
+			fi
+		done
+		sleep .5
+	done
+
+	logit ${_LOG} "${0}: Created _WIN_LIST:${#_WIN_LIST} window(s)"
+}
+
+#--Begin GetOpts--
+local -a OPTIONS
+local OPTION
+local DESC
+
+read -r -d '' DESC<<EOF
+Maximize a window and focus or get window id
+\tBy default, the list of open windows is	queried
+\tuntil the expected title appears or until the 
+\tsearch times out. If option -q is used, the 
+\texpected window must be in the current list of 
+\topen windows and minimum waiting for the title to appear 
+\ttakes place. Optionally, a PID may be used to locate
+\ta window or a WID may be used to identify the window 
+\tdirectly. If option -i is used, a delimited string 
+\tis returned:HEX_ID|DEC_ID|TITLE and no maximizing 
+\ttakes place.
+EOF
+
+parse_opts () {
+	local OPTS=${@}
+	local -a OPTSTR
+	local LETTER_OPT
+	local O
+
+	for O in {1..${#OPTS}};do
+		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
+		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
+		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
+		OPTSTR+="-${OPTS[${O}]}"
+	done
+	echo ${OPTSTR}
+}
+
+opt_exists () {
+	local OPT=${1}
+	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
+}
+
+opt_type () {
+	local OPT=${1}
+	case ${OPT} in
+		d) echo "<DIR>";;
+		f) echo "<FILE>";;
+		p) echo "<PID>";;
+		t) echo "<TITLE>";;
+		w) echo "<WID>";;
+	esac
+}
+
+usage () {
+	local -a PENDING_MSGS=(${@})
+	local OPTS=$(parse_opts ${OPTSTR})
+
+	[[ ${_SMCUP} == 'true' ]] && do_rmcup
+
+	tabs 5
+	(
+	echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [$(opt_type t)]\n"
+	echo -e "${WHITE_FG}-H${RESET} help"
+	echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
+	echo -e "${WHITE_FG}-i${RESET} return window info only - no maximization"
+	echo -e "${WHITE_FG}-p${RESET} $(opt_type p)"
+	echo -e "${WHITE_FG}-q${RESET} quick timeout"
+	echo -e "${WHITE_FG}-w${RESET} $(opt_type w)"
+	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"
+	) >&2
+
+	exit_leave ${PENDING_MSGS}
+}
+
+OPTSTR=":HDip:qw:"
+OPTIND=0
+
+PID_ARG=''
+WID_ARG=''
+GET_ID=false
+
+while getopts ${OPTSTR} OPTION;do
+	case $OPTION in
+     H) usage;;
+     D) dbg_set_level;;
+     i) GET_ID=true;;
+     p) PID_ARG=${OPTARG};;
+     q) _QUICK=true;;
+     w) WID_ARG=${OPTARG};;
+     :) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Option error${RESET}: -${OPTARG} requires an argument"; usage;;
+    \?) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Unknown option${RESET} - ${OPTARG}"; usage;;
+	esac
+	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
+done
+shift $((OPTIND -1))
+#--End GetOpts--
  
-# Args
-APP=${1}
-if [[ -z ${APP} ]];then
-	logit ${_LOG} "Missing argument:APP"
-	return 1
-else
-	logit ${_LOG} "Got APP:${APP}"
+# Execution
+WIN_ARG=${1:l} # Lowercase
+
+WID=''
+EXPECT=''
+if [[ -n ${1} ]];then
+	ARG_TYPE=TITLE
+	EXPECT=$(get_app_tag ${WIN_ARG})
+	WIN_ARG=${EXPECT}
+elif [[ -n ${PID_ARG} ]];then
+	ARG_TYPE=PID
+	WIN_ARG=${PID_ARG}
+elif [[ -n ${WID_ARG} ]];then
+	ARG_TYPE=WID
+	WIN_ARG=${WID_ARG}
 fi
 
-WIN_INFO=$(win_id ${APP})
-if [[ -n ${WIN_INFO} ]];then
-	logit ${_LOG} "Got WIN_INFO:${WIN_INFO} for APP:${APP}"
-	WID=$(cut -d'|' -f1 <<<${WIN_INFO})
-	logit ${_LOG} "Extracted WID:${WID}"
-	wmctrl -i -r ${WID} -b add,maximized_vert,maximized_horz >/dev/null 2>&1
-	logit ${_LOG} "${APP} WID:${WID} was MAXIMIZED"
-	return 0
+[[ -z ${ARG_TYPE} ]] && exit_leave $(err_msg_exit E "Missing argument:$(opt_type t)")
+
+logit ${_LOG} "-- Got ARG:${WIN_ARG}, TYPE:${ARG_TYPE} --"
+
+set_cur_win ${EXPECT} # Create list of open windows
+
+# Get WID
+WIN_ID=$(get_win_id ${WIN_ARG} ${ARG_TYPE})
+
+if [[ -n ${WIN_ID} ]];then
+	logit ${_LOG} "Got WID:${WIN_ID} (${WIN_ARG})"
+	if [[ ${GET_ID} == 'true' ]];then
+		logit ${_LOG} "Returning data for WID:${WIN_ID} (${WIN_ARG})"
+		printf "%s|%d|%s" ${WIN_ID} ${WIN_ID} ${WIN_ARG}
+		return 0
+	else
+		if [[ $(is_maximized ${WIN_ID}) == 'false' ]];then
+			wmctrl -i -r ${WIN_ID} -b add,maximized_vert,maximized_horz >/dev/null 2>&1
+			wmctrl -i -a ${WIN_ID} # Focus
+			logit ${_LOG} "WID:${WIN_ID} (${WIN_ARG}) was MAXIMIZED"
+			return 0
+		else
+			logit ${_LOG} "WID:${WIN_ID} (${WIN_ARG}) was already MAXIMIZED"
+			return 2
+		fi
+	fi
 else
-	logit ${_LOG} "Unable to get WIN_INFO for ${APP}"
+	logit ${_LOG} "Unable to get WIN_ID for ${WIN_ARG}"
 	return 1
 fi
