12-24-2025-13:52:58

diff --git a/LOCAL/yts/yts b/LOCAL/yts/yts
--- a/LOCAL/yts/yts
+++ b/LOCAL/yts/yts
@@ -32,7 +32,7 @@ source ${_LIB_DIR}/LIB_DEPS.zsh
 # Declarations
 typeset -A _CONT_COORDS=()
 typeset -A _ALERT_COORDS=()
-typeset -A _BREAK_COORDS=()
+typeset -A _INFO_COORDS=()
 typeset -A _DISPLAY_KEYS=()
 typeset -A _DOWNLOADS=()
 typeset -A _FAILED=()
@@ -49,8 +49,8 @@ typeset -aU _LOCAL_LIST=()
 
 # Display Constants
 _CONT_COORDS=(X 10 Y $(center -h86) H 10 W 86) # Continuous box coords
-_ALERT_COORDS=(X $(( _CONT_COORDS[X] + 5 )) Y $(( _CONT_COORDS[Y] + _CONT_COORDS[W] - 25 ))) # Alerts display coords
-_BREAK_COORDS=(X $((_CONT_COORDS[X] + 3 )) Y $((_CONT_COORDS[Y] + 3 )) W $((_CONT_COORDS[W] - 6 ))) # Break display coords
+_ALERT_COORDS=(X $(( _CONT_COORDS[X] + 5 )) Y $(( _CONT_COORDS[Y] + _CONT_COORDS[W] - 25 ))) # Error display coords
+_INFO_COORDS=(X $((_CONT_COORDS[X] + 4 )) Y $((_CONT_COORDS[Y] + 3 )) W $((_CONT_COORDS[W] - 6 ))) # Info display coords
 
 # Constants
 _CFG_DIR=~/.local/share/yts
@@ -71,7 +71,7 @@ _MAX_HDR=$(( _CONT_COORDS[W] - 15 ))
 _MAX_TITLE=74
 _MSG_BOX_DISPLAY_AREA=60 # Limit continuous box clearing on Y axis to preserve alert space
 _OBJECT="video"
-_PAUSE_TM=2
+_PAUSE_TM=4
 _SORT_DEFAULT=(youtube 1:a rumble 1:a)
 _YTS_ACRONYMS=${_CFG_DIR}/yts.acronyms
 _YTS_DOWNLOAD_LOG=${_CFG_DIR}/yts.downloads
@@ -102,12 +102,12 @@ g_YTS_LOG=''
 
 # Functions
 action_do () {
-	local -a MSGS
 	local AUTHOR=''
 	local DEST=''
 	local DEST_1=''
 	local DEST_2=''
 	local DL_CNT=0
+	local DL_MSG='Download is complete'
 	local EMSG=''
 	local ERR=''
 	local ERROR_CNT=0
@@ -122,7 +122,7 @@ action_do () {
 	local HRZ_CTR=0
 	local H_CTR=0
 	local INFO_TAG=''
-	local JOB_STALL=10
+	local STALL_LIMIT=10
 	local KEY=''
 	local LAST_LOG_SIZE=0
 	local LAST_LOG_LINE=''
@@ -168,149 +168,102 @@ action_do () {
 		trap job_kill INT
 
 		job_start ${URL}
-		msg_box -x${_CONT_COORDS[X]} -y${_CONT_COORDS[Y]} -h${_CONT_COORDS[H]} -w${_CONT_COORDS[W]} "Download requested..."
+		msg_box -x${_CONT_COORDS[X]} -y${_CONT_COORDS[Y]} -h${_CONT_COORDS[H]} -w${_CONT_COORDS[W]} "<w>Download requested...<N>"
 		sleep 3
 
 		while true;do
 			((NDX++))
 			
-			# Handle job reset
-			KEY=''
-			read -s -t0.1 -k1 KEY
-			if [[ ${KEY} == 'r' ]];then # Process job reset
-				job_reset
-				job_start ${URL}
-				HAD_ERROR=false
-				ERROR_CNT=0
-			fi
-
-			# TODO: Reworking log scan; add error handling and other messages; already downloaded, etc.
-			{ LOG_LINE=$(sed -e 's//\n/g' -e '/./!d' ${g_YTS_LOG} | tail -1 | str_trim) } 2>/dev/null
-
-			logit ${_YT_DBG_LOG} "${0}:${LOG_LINE}"
-
-			# Label log msg types
-			if grep -Eiq '^\[youtube\]|^\[rumble\]' <<<${LOG_LINE};then 
-				SECTION=SITE
-			elif grep -Eiq '^\[info\]' <<<${LOG_LINE};then 
-				SECTION=INFO
-			elif grep -Eiq '^\[hlsnative\]' <<<${LOG_LINE};then 
-				SECTION=HLS
-			elif grep -Eiq '^\[download\]' <<<${LOG_LINE};then 
-				SECTION=DOWWNLOAD
-			elif grep -Eiq '^\[fixupm3u8\]' <<<${LOG_LINE};then 
-				SECTION=FFMPEG
-			elif grep -Eiq '^ERROR' <<<${LOG_LINE};then 
-				SECTION=ERROR
-			else
-				SECTION=UNKNOWN
-				logit ${_YT_DBG_LOG} "${0}: SECTION:${SECTION} UNCAPTURED:${LOG_LINE}"
-			fi
-
-			# Parse log messages within type
-			if [[ ${SECTION} == 'ERROR' ]];then
-				# Scan for future notice
-				if grep -Eiq 'will begin|premieres|upcoming' <<<${LOG_LINE};then
-					logit ${_YT_DBG_LOG} "${0}: FUTURE:${LOG_LINE}"
-					EMSG="<w>${TITLE[1,65]}<N>|<r>Not yet available<N>|<g>$(str_word_clip ${LOG_LINE} ${_MAX_HDR})<N>"
-					[[ ! ${LOG_LINE} =~ 'minute*|hour*|day*' ]] && g_WHEN='soon' || g_WHEN=$(perl -pe 's/^(.*) in (\d+\s+\w+)(.*)$/\2/g' <<<${LOG_LINE})
-					msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-					_FUTURE[${M}]=true
-					_DOWNLOADS[${M}]=false
-					break # Scan cycle
-				else
-					logit ${_YT_DBG_LOG} "${0}: SECTION:${SECTION} UNCAPTURED:${LOG_LINE}"
-				fi
-			elif [[ ${SECTION} == 'SITE' ]];then
-				EMSG="<w>${TITLE[1,65]}<N>|<g>Pre-processing<N>|<w>$(str_word_clip ${LOG_LINE} ${_MAX_HDR})<N>"
-				msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-			elif [[ ${SECTION} == 'INFO' ]];then
-				EMSG="<w>${TITLE[1,65]}<N>|<g>Pre-processing<N>|<w>$(str_word_clip ${LOG_LINE} ${_MAX_HDR})<N>"
-				msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-			elif [[ ${SECTION} == 'HLS' ]];then
-				EMSG="<w>${TITLE[1,65]}<N>|<g>Pre-processing<N>|<w>$(str_word_clip ${LOG_LINE} ${_MAX_HDR})<N>"
-				msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-			elif [[ ${SECTION} == 'DOWWNLOAD' ]];then
-				grep -Eiq "already been downloaded" ${g_YTS_LOG} 2>/dev/null # Whole file grep
-				if [[ ${?} -eq 0 ]];then
-					logit ${_YT_DBG_LOG} "${0}: LOG_LINE:${LOG_LINE}"
-					EMSG="<w>${TITLE[1,65]}<N>|<g>Has already been downloaded<N>" 
-					msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-					_DOWNLOADS[${M}]=true
-					break # Scan cycle
-				elif grep -Eiq 'sleeping' <<<${LOG_LINE};then
-					EMSG="<w>${TITLE[1,65]}<N>|<g>Pre-processing<N>|<w>$(str_word_clip ${LOG_LINE} ${_MAX_HDR})<N>"
-					msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-				elif [[ ${HDRS_OUT} == 'false' ]];then
-					DEST=$(grep -m1 -i "destination" ${g_YTS_LOG} 2>/dev/null) # Whole file grep
-					if [[ -z ${DEST} ]];then
-						DEST="QUERY FAILED - DEST UNSET"
-					else
-						DEST=("${(f)$(sed -e "s#${_DOWNLOAD_DIR}/#${_DOWNLOAD_DIR}|#g" -e 's/ \[.*//g' <<<${DEST})}") # Strip path
-						DEST_1=$(cut -d'|' -f1 <<<${DEST})
-						DEST_1=$(cut -d']' -f2- <<<${DEST_1} | sed -e "s/^[[:space:]]/<w>/" -e "s/:/<N>:<m>/")
+			# Ensure log activity
+			LOG_SIZE=$(wc -c < ${g_YTS_LOG} 2>/dev/null)
+			if [[ ${LOG_SIZE} -ne ${LAST_LOG_SIZE} ]];then
+				LOG_STALLS=0 # Log is growing
+				if [[ ${?} -eq 0 && ${HDRS_OUT} == 'false' ]];then
+					LOG_LINE=$(tail -1 ${g_YTS_LOG}) # Get most recent log line
+					logit ${_YT_DBG_LOG} "${0}:${LOG_LINE}"
+					if [[ ${LOG_LINE} =~ '^\[info\]' ]];then # Look for pre-processing
+						MSG=${LOG_LINE[1,56]}
+						[[ ${MSG} != ${LAST_LOG_LINE} ]] && msg_box -t ${_PAUSE_TM} -x${_INFO_COORDS[X]} -y${_INFO_COORDS[Y]} "<c>Pre-processing...${MSG}<N>"
+						LAST_LOG_LINE=${MSG}
+						continue
+					elif [[ ${LOG_LINE} =~ 'sleeping' ]];then # Look for pre-processing
+						MSG=${LOG_LINE[1,56]}
+						[[ ${MSG} != ${LAST_LOG_LINE} ]] && msg_box -t ${_PAUSE_TM} -x${_INFO_COORDS[X]} -y${_INFO_COORDS[Y]} "<c>Pre-processing...${MSG}<N>"
+						LAST_LOG_LINE=${MSG}
+						continue
+					elif [[ ${LOG_LINE:l} =~ 'error' ]];then # Look for errors
+						logit ${_YT_DBG_LOG} "${0}:${LOG_LINE}"
+						if [[ ${LOG_LINE:l} =~ 'will begin|premieres|upcoming' ]];then
+							[[ ! ${LOG_LINE} =~ 'minute*|hour*|day*' ]] && g_WHEN='soon' || g_WHEN=$(perl -pe 's/^(.*) in (\d+\s+\w+)(.*)$/\2/g' <<<${LOG_LINE})
+							MSG="<w>${TITLE[1,65]}<N>|<r><B>Not yet available<N> - Airing time:<w>${g_WHEN}<N>"
+							[[ ${MSG} != ${LAST_LOG_LINE} ]] && msg_box -t ${_PAUSE_TM} -z -x ${_INFO_COORDS[X]} -y ${_INFO_COORDS[Y]} -w ${_INFO_COORDS[W]} "${MSG}"
+							_FUTURE[${M}]=true
+							_DOWNLOADS[${M}]=false
+							break
+						elif [[ ${LOG_LINE:l} =~ 'unable to download' ]];then
+							MSG="<w>${TITLE[1,56]}<N>|<r>Transmission error<N>:${LOG_LINE}"
+							[[ ${MSG} != ${LAST_LOG_LINE} ]] && msg_box -t ${_PAUSE_TM} -z -x ${_INFO_COORDS[X]} -y ${_INFO_COORDS[Y]} -w ${_INFO_COORDS[W]} "${MSG}"
+							_DOWNLOADS[${M}]=false
+							break
+						else
+							MSG="<r>Got undefined error<N>:${LOG_LINE[1,56]}"
+							[[ ${MSG} != ${LAST_LOG_LINE} ]] && msg_box -t ${_PAUSE_TM} -z -x ${_INFO_COORDS[X]} -y ${_INFO_COORDS[Y]} -w ${_INFO_COORDS[W]} "${MSG}"
+						fi
+						LAST_LOG_LINE=${MSG}
+						continue
+					else # Pre-processing complete
+						LOG_LINE=$(grep --color=never -Ei 'destination:' ${g_YTS_LOG}) # Get destination
 					fi
-					HDR1_TXT=$(cut -d'|' -f2 <<<${DEST:r} | sed 's/_/ /g') # Clear space fillers and file extension
-					HDR1_TXT=$(clean_title ${HDR1_TXT})
-					HDR1_TXT=$(str_word_clip ${HDR1_TXT} ${_MAX_HDR})
-					HDR1_TXT="<w>Downloading<N>:<m> <c>${HDR1_TXT}<N>"
-					HDR2_TXT="$(str_trim ${DEST_1})<N> - <w>${DL_CNT} <N>of <w>${#_MARKED}<N>${INFO_TAG}"
-					HDR_LEN=$(( ${#$(msg_nomarkup ${HDR2_TXT})} ))
-					HDR_LEN=$(( HDR_LEN + FRAME_PAD ))
-					HRZ_CTR=$(center -h${HDR_LEN}) # Horiz center
-					[[ ${HDR_LEN} -gt ${_CONT_COORDS[W]} ]] && _CONT_COORDS[W]=${HDR_LEN} && _CONT_COORDS[Y]=${HRZ_CTR} # Adjust frame width/center
-					msg_box -c -C -I -H3 -jl -x${_CONT_COORDS[X]} -y${_CONT_COORDS[Y]} -h${_CONT_COORDS[H]} -w${_CONT_COORDS[W]} ${HDR1_TXT}
-					msg_box -C -jl ${HDR2_TXT}
-					msg_box -C -jl "<c>$(str_unicode_line $(( _CONT_COORDS[W] - 2 )))<N>" # Divider line
-					HDRS_OUT=true
-				elif grep -Eq 'ETA' <<<${LOG_LINE};then
-					ETA=''
-					ETA_COMPLETE=false
-					ETA=${LOG_LINE}
-					[[ ${ETA} =~ '100%' ]] && ETA_COMPLETE=true
-				else
-					logit ${_YT_DBG_LOG} "${0}: SECTION:${SECTION} UNCAPTURED:${LOG_LINE}"
-				fi
-			elif [[ ${SECTION} == 'FFMPEG' ]];then
-				ETA_COMPLETE=true
-				EMSG="<w>${TITLE[1,65]}<N>|<g>Post-processing<N>|<w>$(str_word_clip ${LOG_LINE} ${_MAX_HDR})<N>"
-				msg_box -z -x ${_BREAK_COORDS[X]} -y ${_BREAK_COORDS[Y]} -w ${_BREAK_COORDS[W]} -t${_PAUSE_TM} "${EMSG}"
-			else
-				logit ${_YT_DBG_LOG} "${0}: SECTION:${SECTION} UNCAPTURED:${LOG_LINE}"
-			fi
-
-			if [[ -n ${ETA} ]];then
-				LINE_COLOR=''
-				ERROR_CNT=0 
-				SPEED=$(get_speed ${ETA})
-				download_indicator ${SPEED}
-				if [[ ${ETA_COMPLETE} == 'true' ]];then
-					LINE_COLOR='<B><g>' && ETA="100% of download completed"
-				else
-					case ${ETA:l} in
-						*mib/s*) LINE_COLOR='<w>';;
-						*kib/s*) LINE_COLOR='<B><y>';;
-						*) continue;; # Skip other
-					esac
+				else # Transfer info
+					LOG_LINE=$(tr '' '\n' < ${g_YTS_LOG} | tail -1 | str_trim) 2>/dev/null # Break into separate lines - get most recent
+					logit ${_YT_DBG_LOG} "${0}:${LOG_LINE}"
 				fi
 			else
-				logit ${_YT_DBG_LOG} "${0}: UNCAPTURED"
-				continue # Uncaptured line
+				((LOG_STALLS++))
+				if [[ ${LOG_STALLS} -ge ${STALL_LIMIT} ]];then
+					msg_box -x${_INFO_COORDS[X]} -y${_INFO_COORDS[Y]} "<r>No Log Activity - Exiting<N>"
+					exit_leave "No log activity"
+				fi
+				LAST_LOG_SIZE=${LOG_SIZE}
 			fi
 
-			[[ ${HAD_ERROR} == 'true' ]] && LINE_COLOR='<r>'
-
-			msg_box -C -jl "${LINE_COLOR}${ETA[1,59]}<N>" # Show progress
-
-			if [[ ${ETA_COMPLETE} == 'true'  ]];then
+			# Process log line
+			if [[ ${LOG_LINE:l} =~ 'destination:' ]];then
+				DEST=("${(f)$(sed -e "s#${_DOWNLOAD_DIR}/#${_DOWNLOAD_DIR}|#g" -e 's/ \[.*//g' <<<${LOG_LINE})}") # Strip path
+				DEST_1=$(cut -d'|' -f1 <<<${DEST})
+				DEST_1=$(cut -d']' -f2- <<<${DEST_1} | sed -e "s/^[[:space:]]/<w>/" -e "s/:/<N>:<m>/")
+				HDR1_TXT=$(cut -d'|' -f2 <<<${DEST:r} | sed 's/_/ /g') # Clear space fillers and file extension
+				HDR1_TXT="<w>Downloading<N>:<m> <c>$(clean_title ${HDR1_TXT} ${_MAX_HDR})<N>"
+				HDR2_TXT="$(str_trim ${DEST_1})<N> - <w>${DL_CNT} <N>of <w>${#_MARKED}<N>${INFO_TAG}"
+				HDR_LEN=$(( ${#$(msg_nomarkup ${HDR2_TXT})} ))
+				HDR_LEN=$(( HDR_LEN + FRAME_PAD ))
+				HRZ_CTR=$(center -h${HDR_LEN}) # Horiz center
+				[[ ${HDR_LEN} -gt ${_CONT_COORDS[W]} ]] && _CONT_COORDS[W]=${HDR_LEN} && _CONT_COORDS[Y]=${HRZ_CTR} # Adjust frame width/center
+				msg_box -c -C -I -H3 -jl -x${_CONT_COORDS[X]} -y${_CONT_COORDS[Y]} -h${_CONT_COORDS[H]} -w${_CONT_COORDS[W]} ${HDR1_TXT}
+				msg_box -C -jl ${HDR2_TXT}
+				msg_box -C -jl "<c>$(str_unicode_line $(( _CONT_COORDS[W] - 2 )))<N>" # Divider line
+				HDRS_OUT=true
+			elif [[ ${LOG_LINE} =~ 'ETA' ]];then
+				SPEED=$(get_speed ${LOG_LINE}) && download_indicator ${SPEED}
+				ETA_COMPLETE=false
+				ETA=${LOG_LINE}
+				case ${LOG_LINE:l} in
+					*100%*) LINE_COLOR='<B><g>';ETA_COMPLETE=true;logit ${_YT_DBG_LOG} "HIT 100%";;
+					*mib/s*) LINE_COLOR='<w>';;
+					*kib/s*) LINE_COLOR='<B><y>';;
+				esac
+				msg_box -C -jl "${LINE_COLOR}${ETA[1,59]}<N>" # Show progress
+			elif [[ ${ETA_COMPLETE} == 'true' || ${LOG_LINE:l} =~ 'fixing mpeg-ts|fixupm3u8' ]];then
+				logit ${_YT_DBG_LOG} "COMPLETED MSG"
+				msg_box -C -jl "<B><g>${DL_MSG}<N>" # Show completed message
 				_DOWNLOADS[${M}]=true
 				post_process
 				log_add ${M}
-				break # Scan cycle
-			fi # Monitor progress
+				break
+			fi
 
 			sleep .5 # Log fetch delay
-		done # Log scan complete
+		done
 		NDX=0
 		log_clear "action_do"
 		sleep 1 # Job request delay
@@ -361,6 +314,20 @@ box_center () {
 	local TXT_LEN=$(( ${#TXT} + BOX )) # Text length
 
 	echo $(center -y${BOX} -t${BOX_WIDTH} ${TXT})
+}
+
+cfg_init () {
+	local CFG_STATE=0
+	local -A CFG_MSGS=(1 "Missing configuration directory:${_CFG_DIR}" 2 "Missing favorites file:${_YTS_FAVORITES}")
+
+	[[ -e ${_YT_DBG_LOG} ]] && /bin/rm -f ${_YT_DBG_LOG}
+
+	[[ -d ${_CFG_DIR} ]] && CFG_STATE=0 || CFG_STATE=1
+	[[ -f ${_YTS_FAVORITES} ]] && CFG_STATE=0 || CFG_STATE=2
+
+	echo ${CFG_MSGS[${CFG_STATE}]}
+
+	return ${CFG_STATE}
 }
 
 clean_title () {
@@ -576,6 +543,59 @@ download_select () {
 	_FUTURE=()
 }
 
+fav_add () {
+	local FAVORITE=$(str_trim ${1:gs/ /_/})
+	local -aU HISTORY
+	local LINE=''
+	local LTYPE=''
+	local FTYPE=''
+	local H
+
+	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
+	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ARG: FAVORITE:${FAVORITE} g_QRY_ENGINE:${g_QRY_ENGINE}"
+
+	clear
+
+	msg_box -H1 -p -PC "<w><I>Please respond<N>|<Z>|Add \"${(C)${FAVORITE:gs/_/ /}}\" to favorites?"
+	[[ ${_MSG_KEY} != 'y' ]] && return
+
+	while true;do
+		msg_box -c -H1 -p -PS -jl "<w>Select Favorites List<N>|<Z>|y) YouTube|r) Rumble|c) Custom"
+		case ${_MSG_KEY:l} in
+			y) LTYPE=y && break;;
+			r) LTYPE=r && break;;
+			c) LTYPE=c && break;;
+			0) return;;
+			*) msg_box -p -PK "Invalid option";;
+		esac
+	done
+
+	case ${g_QRY_ENGINE} in
+		youtube) [[ ${g_STRICT} == 'true' ]] && FTYPE="YS" || FTYPE="Y";;
+		rumble) [[ ${g_PREFER_LIVE} == 'true' ]] && FTYPE="RL" || FTYPE="R";;
+	esac
+
+	[[ ${LTYPE} == 'c' ]] && FTYPE="P${FTYPE}"
+
+	FAVORITE="${(C)FAVORITE}|${FAVORITE}|${FTYPE}"
+
+	HISTORY+=${FAVORITE}
+
+	if [[ -e ${_YTS_FAVORITES} ]];then
+		while read LINE;do
+			HISTORY+=${LINE}
+		done < ${_YTS_FAVORITES}
+
+		/bin/rm -f ${_YTS_FAVORITES}
+	fi
+
+	for H in ${(o)HISTORY};do
+		echo ${H} >> ${_YTS_FAVORITES}
+	done
+
+	sort -o ${_YTS_FAVORITES} -t'|' -k3 ${_YTS_FAVORITES} 
+}
+
 fav_delete () {
 	local FAV=${1:gs/ /_/:l}
 	local ENG=''
@@ -609,7 +629,9 @@ fav_delete () {
 			else
 				mv -f ${_YTS_FAV_NEW} ${_YTS_FAVORITES}
 				logit ${_YT_DBG_LOG} "${0}: log ${_YTS_FAVORITES} updated"
-				fav_load
+				if ! fav_load;then
+					exit_leave "Unable to load favorites"
+				fi
 			fi
 		else
 			exit_leave "No favorites have been saved"
@@ -716,65 +738,16 @@ fav_load () {
 
 	_FAV_LIST=()
 
+	[[ ! -f ${_YTS_FAVORITES} ]] && return 1
+
 	while read LINE;do
 		D_KEY=$(cut -d'|' -f1 <<<${LINE})
 		Q_KEY=$(cut -d'|' -f2 <<<${LINE})
 		Q_OPT=$(cut -d'|' -f3 <<<${LINE})
 		_FAV_LIST[${D_KEY}]="${Q_KEY}:${Q_OPT}"
 	done < ${_YTS_FAVORITES}
-}
 
-fav_add () {
-	local FAVORITE=$(str_trim ${1:gs/ /_/})
-	local -aU HISTORY
-	local LINE=''
-	local LTYPE=''
-	local FTYPE=''
-	local H
-
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ARG: FAVORITE:${FAVORITE} g_QRY_ENGINE:${g_QRY_ENGINE}"
-
-	clear
-
-	msg_box -H1 -p -PC "<w><I>Please respond<N>|<Z>|Add \"${(C)${FAVORITE:gs/_/ /}}\" to favorites?"
-	[[ ${_MSG_KEY} != 'y' ]] && return
-
-	while true;do
-		msg_box -c -H1 -p -PS -jl "<w>Select Favorites List<N>|<Z>|y) YouTube|r) Rumble|c) Custom"
-		case ${_MSG_KEY:l} in
-			y) LTYPE=y && break;;
-			r) LTYPE=r && break;;
-			c) LTYPE=c && break;;
-			0) return;;
-			*) msg_box -p -PK "Invalid option";;
-		esac
-	done
-
-	case ${g_QRY_ENGINE} in
-		youtube) [[ ${g_STRICT} == 'true' ]] && FTYPE="YS" || FTYPE="Y";;
-		rumble) [[ ${g_PREFER_LIVE} == 'true' ]] && FTYPE="RL" || FTYPE="R";;
-	esac
-
-	[[ ${LTYPE} == 'c' ]] && FTYPE="P${FTYPE}"
-
-	FAVORITE="${(C)FAVORITE}|${FAVORITE}|${FTYPE}"
-
-	HISTORY+=${FAVORITE}
-
-	if [[ -e ${_YTS_FAVORITES} ]];then
-		while read LINE;do
-			HISTORY+=${LINE}
-		done < ${_YTS_FAVORITES}
-
-		/bin/rm -f ${_YTS_FAVORITES}
-	fi
-
-	for H in ${(o)HISTORY};do
-		echo ${H} >> ${_YTS_FAVORITES}
-	done
-
-	sort -o ${_YTS_FAVORITES} -t'|' -k3 ${_YTS_FAVORITES} 
+	[[ -n ${_FAV_LIST} ]] && return 0 || return 1
 }
 
 get_field () {
@@ -1138,7 +1111,7 @@ post_process () {
 		if [[ ${?} -ne 0 ]];then
 			sleep 2 && break
 		fi
-		msg_box -x14 "(<w>${NDX}<N>) Waiting for <c>yt-dlp<N> to finish postprocessing..."
+		msg_box -x14 "(<w>${NDX}<N>) Waiting for <c>yt-dlp<N> to finish post-processing..."
 		sleep 1
 	done
 
@@ -1591,6 +1564,11 @@ shift $(( OPTIND  - 1 ))
 #--End GetOpts--
 
 # Execution
+CFG_MSG=$(cfg_init)
+if [[ ${?} -ne 0 ]];then
+	exit_leave "Configuration failed:${CFG_MSG}"
+fi
+
 [[ -n ${WEB} ]] && website ${WEB} && exit_leave
 
 [[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "ARGS IN:${@}, g_QRY_ENGINE:${g_QRY_ENGINE}"
@@ -1669,7 +1647,9 @@ log_update # Update the log
 clear
 
 # Load favorites
-fav_load ${_FAV_TAB}
+if ! fav_load;then
+	exit_leave "Unable to load favorites"
+fi
 
 # Load acronyms
 if [[ -e ${_YTS_ACRONYMS} ]];then
