01-08-2026-01:17:25

diff --git a/LOCAL/yts/yts b/LOCAL/yts/yts
--- a/LOCAL/yts/yts
+++ b/LOCAL/yts/yts
@@ -30,24 +30,26 @@ source ${_LIB_DIR}/LIST.zsh
 source ${_LIB_DIR}/LIB_DEPS.zsh
 
 # Declarations
-typeset -A _CONT_COORDS=()
 typeset -A _ALERT_COORDS=()
-typeset -A _INFO_COORDS=()
+typeset -A _CONT_COORDS=()
 typeset -A _DOWNLOADS=()
 typeset -A _FAILED=()
 typeset -A _FAV_LIST=()
 typeset -A _FIELD_LEN=()
 typeset -A _FUTURE=()
+typeset -A _INFO_COORDS=()
 typeset -A _PARTIALS=()
+typeset -A _QUERY_MAP=(l live g general u user c channel)
 typeset -A _QUERY_OPTS=()
 typeset -A _REJECTS=()
+typeset -A _RUMBLE_ROWS=()
 typeset -A _SEEN=()
 typeset -A _SORT_TABLE=()
 typeset -A _STATUS_MSGS=()
 typeset -a _ACRONYMS=()
-typeset -aU _LOCAL_LIST=()
 typeset -a _QUERY_TYPES=(l c u g)
-typeset -A _QUERY_MAP=(l live g general u user c channel)
+typeset -a _RUMBLE_PAGE=()
+typeset -aU _LOCAL_LIST=()
 
 # Display Constants
 _CONT_COORDS=(X 10 Y $(center -h86) H 10 W 86) # Continuous box coords
@@ -504,14 +506,14 @@ download_select () {
 		[[ ${_QUERY_OPTS[STRICT]} == 'true' ]] && SEARCHTYPE="Strict (${_QUERY_OPTS[SMSG]} rejected)"
 	fi
 
- # Set headings
+	# Set headings
 	list_set_header_init
 	list_set_header 'printf "Found:${WHITE_FG}%-d${RESET} $(str_pluralize video ${#_LIST})\tPlatform:${WHITE_FG}%s${RESET}\tQuery Key:${WHITE_FG}%s${RESET}\tQuery Type:${WHITE_FG}%s${RESET}\tSelected:${WHITE_FG}%s${RESET}\t${_PG}" ${#_LIST} ${(C)_QUERY_OPTS[ENGINE]} ${(C)SEARCHTERM} ${(C)_QUERY_OPTS[TYPE]} $(list_get_selected_count)'
 	list_set_header 'printf " "'
 	list_set_header 'printf "%*s %-*s %-*s %-*s" 5 "" ${_FIELD_LEN[age]} "Age" ${_FIELD_LEN[author]} "Author" ${_FIELD_LEN[title]} "Title"'
 	list_set_header 'printf "%*s ${SCOL1_CLR}%-*s${RESET} ${SCOL2_CLR}%*s${RESET} ${SCOL3_CLR}%*s${RESET}" 5 "" ${_FIELD_LEN[age]} "$(str_unicode_line ${_FIELD_LEN[age]})" ${_FIELD_LEN[author]} "$(str_unicode_line ${_FIELD_LEN[author]})" ${_FIELD_LEN[title]} "$(str_unicode_line ${_FIELD_LEN[title]})"'
 
- # Set line item
+	# Set line item
 	list_set_line_item ' 
 	local ITEM_COLOR=$(set_item_color $(item_decorate ${_LIST_NDX}));
 	printf "${BOLD}${WHITE_FG}%4s${RESET}${_MARKER} ${SHADE}${BAR}${ITEM_COLOR}%-${_FIELD_LEN[age]}s${RESET}${SHADE}${BAR} %-${_FIELD_LEN[author]}s %-${_FIELD_LEN[title]}s${RESET}\n" ${_LIST_NDX} "$(item_decorate ${_LIST_NDX})"  "$(get_field author ${_LIST_NDX})"  "$(get_field title ${_LIST_NDX})" 
@@ -763,7 +765,7 @@ get_field () {
 	fi
 
 	if [[ ${FIELD} == 'author' ]];then
-		if [[ ${_QUERY_OPTS[QKEY]} =~ ' ' ]];then # Query key contains a space - assume multiple authors
+		if [[ ${_QUERY_OPTS[QKEY]} =~ ' ' ]];then # Query key contains a space - assume multiple authors are displayed
 			STR=$(str_trim <<<${STR})
 			[[ -z ${STR} ]] && STR=${_QUERY_OPTS[DKEY]} # Ensure not blank
 		else
@@ -981,27 +983,31 @@ log_find () {
 		[[ ${DBG} == 'true' ]] && echo "LIST_TM:${LIST_TM}" >>${0}.dbg
 		[[ ${DBG} == 'true' ]] && echo "\nAttempting TITLE match on:${LIST_TITLE[1,50]}" >>${0}.dbg 
 
-		LOG_TITLE=$(grep -F -n -m1 -i -- ${LIST_TITLE[1,50]} ${_YTS_DOWNLOAD_LOG}) # grep -F option needed to ignore any special chars
-		if [[ ${?} -eq 0 ]];then
-			LINE_NUM=$(cut -d: -f1 <<<${LOG_TITLE}) # Fetch line number
-			LOG_LINE=$(sed -n "${LINE_NUM}p" ${_YTS_DOWNLOAD_LOG}) # Fetch log line
-			LOG_AU=$(grep -i -o -m1 "${LIST_AU}$" <<<${LOG_LINE}) # Match author in log line
-			LOG_TM=$(grep -o ${LIST_TM} <<<${LOG_LINE}) # Match time in log line
+		if [[ -n ${LIST_TITLE[1,50]} ]];then
+			LOG_TITLE=$(grep -F -n -m1 -i -- ${LIST_TITLE[1,50]} ${_YTS_DOWNLOAD_LOG}) # grep -F option needed to ignore any special chars
+			if [[ ${?} -eq 0 ]];then
+				LINE_NUM=$(cut -d: -f1 <<<${LOG_TITLE}) # Fetch line number
+				LOG_LINE=$(sed -n "${LINE_NUM}p" ${_YTS_DOWNLOAD_LOG}) # Fetch log line
+				LOG_AU=$(grep -i -o -m1 "${LIST_AU}$" <<<${LOG_LINE}) # Match author in log line
+				LOG_TM=$(grep -o ${LIST_TM} <<<${LOG_LINE}) # Match time in log line
 
-			[[ ${DBG} == 'true' ]] && echo "Matched:TITLE:${LOG_TITLE}" >>${0}.dbg
-			[[ ${DBG} == 'true' ]] && echo "Log line:${LOG_LINE}" >>${0}.dbg
-			[[ ${DBG} == 'true' ]] && echo "Author:${LIST_AU} Time:${LIST_TM}" >>${0}.dbg
+				[[ ${DBG} == 'true' ]] && echo "Matched:TITLE:${LOG_TITLE}" >>${0}.dbg
+				[[ ${DBG} == 'true' ]] && echo "Log line:${LOG_LINE}" >>${0}.dbg
+				[[ ${DBG} == 'true' ]] && echo "Author:${LIST_AU} Time:${LIST_TM}" >>${0}.dbg
 
-			if [[ -n ${LOG_TM} && -n ${LOG_AU} ]];then
-				LOG_FN=$(cut -d '|' -f3 <<<${LOG_LINE}) # Fetch filename
-				_DOWNLOADS[${R}]=true
+				if [[ -n ${LOG_TM} && -n ${LOG_AU} ]];then
+					LOG_FN=$(cut -d '|' -f3 <<<${LOG_LINE}) # Fetch filename
+					_DOWNLOADS[${R}]=true
 
-				[[ ${DBG} == 'true' ]] && echo "Confirmed match: Marking NDX:${R} as downloaded for file:${LOG_FN}\n" >>${0}.dbg
-				[[ ${DBG} == 'true' ]] && echo "LOG_AU:${LOG_AU}" >>${0}.dbg
-				[[ ${DBG} == 'true' ]] && echo "LOG_TM:${LOG_TM}" >>${0}.dbg
-			else
-				[[ ${DBG} == 'true' ]] && echo "Failed to confirm download" >>${0}.dbg
+					[[ ${DBG} == 'true' ]] && echo "Confirmed match: Marking NDX:${R} as downloaded for file:${LOG_FN}\n" >>${0}.dbg
+					[[ ${DBG} == 'true' ]] && echo "LOG_AU:${LOG_AU}" >>${0}.dbg
+					[[ ${DBG} == 'true' ]] && echo "LOG_TM:${LOG_TM}" >>${0}.dbg
+				else
+					[[ ${DBG} == 'true' ]] && echo "Failed to confirm download" >>${0}.dbg
+				fi
 			fi
+		else
+			logit ${_YT_DBG_LOG} "${0}: Skipped title search - blank title"
 		fi
 	done
 }
@@ -1121,25 +1127,88 @@ post_process () {
 	set_final_fn ${FN}
 }
 
-query_rumble () {
-	local -a AUTHORS=()
-	local -A FIELD_MAP=("author" 1 "title" 2 "age" 3 "url" 4 "time" 5 "agetime" "3,5")
-	local -A LAST_MSG=($(box_coords_get ${_LAST_MSG_TAG}))
-	local -a NDX_OUT=()
-	local -a TMP=()
+parse_rumble () {
+	local PARSE_TYPE=${1}
+	local -A GENERAL=()
+	local -A NON_GENERAL=()
+	local -a HTML=()
+	local DATA=''
+	local LAST_ROW=0
+	local LINE=''
+	local NDX=0
+	local ROW=0
+	local TAB=''
+	local TAG=''
+	local TAGLINE=''
+	local TAG_ARRAY=''
 	local AGE AUTHOR TITLE URL TIME AGETIME
+	local K
+
+	[[ -z ${_RUMBLE_PAGE} ]] && return 1 # No data returned from query
+
+	NON_GENERAL[TITLES]='thumbnail__title attr{title}'
+	NON_GENERAL[LINKS]='title__link attr{href}'
+	NON_GENERAL[AGES]='videostream__time text{}'
+	NON_GENERAL[DURATIONS]='videostream__badge text{}'
+
+	GENERAL[AUTHORS]='ellipsis-1 text{}'
+	GENERAL[TITLES]='video-item--title text{}'
+	GENERAL[LINKS]='video-item--a attr{href}'
+	GENERAL[AGES]='video-item--time text{}'
+	GENERAL[DURATIONS]='video-item--duration attr{data-value}'
+
+	if [[ ${PARSE_TYPE} == 'g' ]];then
+		TAG_ARRAY="GENERAL"
+		TAGLINE="\"video-item--img\""
+	else
+		TAG_ARRAY="NON_GENERAL"
+		TAGLINE="thumbnail__grid--item"
+	fi
+
+	ROW=0
+	while read LINE;do
+		HTML+=${LINE}
+		if [[ ${LINE} =~ ${TAGLINE} ]];then
+			for K in ${(k)${(P)TAG_ARRAY}};do
+				TAG=${${(P)TAG_ARRAY}[${K}]}
+				DATA=$(pup --charset utf8 ".${TAG}" <<<${HTML} | strip_unwanted)
+				#echo "${ROW} ${TAG} ${DATA}" >>row_data
+				if [[ ${ROW} -ne 0 && -n ${DATA} ]];then
+					_RUMBLE_ROWS[${ROW}_${K}]=${DATA}
+				fi
+			done
+			((ROW++))
+			HTML=()
+		fi
+	done <<<${_RUMBLE_PAGE}
+
+	LAST_ROW=1
+	for K in ${(onk)_RUMBLE_ROWS};do
+		ROW=$(cut -d'_' -f1 <<<${K})
+		TAB=$(cut -d'_' -f2 <<<${K})
+		case ${TAB} in
+			AGES) AGE=${_RUMBLE_ROWS[${K}]};;
+			AUTHORS) AUTHOR=${_RUMBLE_ROWS[${K}]};;
+			DURATIONS) TIME=${_RUMBLE_ROWS[${K}]};;
+			LINKS) URL="https://rumble.com${_RUMBLE_ROWS[${K}]}";;
+			TITLES) TITLE=${_RUMBLE_ROWS[${K}]};;
+		esac
+		if [[ ${ROW} != ${LAST_ROW} ]];then
+			[[ ${URL} =~ 'ucp_f' ]] && LAST_ROW=${ROW} && continue # Omit featured links
+			AGETIME="(${AGE} ${TIME})"
+			[[ -z ${AUTHOR} ]] && AUTHOR=${_QUERY_OPTS[DKEY]}
+			_LOCAL_LIST[${ROW}]="${AGE}|${AUTHOR}|${TITLE}|${URL}|${TIME}|${AGETIME}"
+			#echo "${ROW} ${AGE}|${AUTHOR}|${TITLE}|${URL}|${TIME}|${AGETIME}\n-------------------------------------------" >>row_data
+			AGE='' && AUTHOR='' && TIME='' && URL='' && TITLE=''
+		fi
+		LAST_ROW=${ROW}
+	done
+}
+
+query_rumble () {
 	local GEN_SEARCH=''
-	local QRY_TYPE=''
-	local MSG=''
-	local NDX=''
-	local PG=''
 	local QRY=''
-	local STR=''
-	local -a TITLES=()
-	local -a LINKS=()
-	local -a AGES=()
-	local -a DURATIONS=()
-	local L
+	local QRY_TYPE=''
 
 	QRY_TYPE=${_QUERY_MAP[${_QUERY_OPTS[EOPT]:l}]}
 	[[ -z ${QRY_TYPE} ]] && msg_box -p -PK "${0}:Invalid query type:${_QUERY_OPTS[EOPT]}" && return 1
@@ -1150,134 +1219,34 @@ query_rumble () {
 
 	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
 
+	# Queries
 	if [[ ${QRY_TYPE} == 'live' ]];then
 		msg_box -c "Requesting <c><I>livestream channel<N> search..."
-
 		QRY="https://rumble.com/c/${_QUERY_OPTS[QKEY]}/livestreams"
-
-		PG=$(wget -q -O - ${QRY})
-		wget -q -O - ${QRY} > ${_CFG_DIR}/Rumble.qry
-
-		TITLES=("${(f)$(pup --charset utf8 '.thumbnail__title attr{title}' <<< ${PG})}")
-		LINKS=("${(f)$(pup --charset utf8 '.title__link attr{href}' <<< ${PG})}")
-		AGES=("${(f)$(pup --charset utf8 '.videostream__time text{}' <<< ${PG} | strip_space)}")
-		DURATIONS=("${(f)$(pup --charset utf8 '.videostream__badge text{}' <<< ${PG} | strip_space | grep -E '[0-9].*')}")
+		_RUMBLE_PAGE=$(wget -q -O - ${QRY})
 	elif [[ ${QRY_TYPE} == 'channel' ]];then
 		msg_box -c "Requesting <c><I>channel<N> search..."
-
 		QRY="https://rumble.com/c/${_QUERY_OPTS[QKEY]}?page=1"
-
-		PG=$(wget -q -O - ${QRY})
-		wget -q -O - ${QRY} > ${_CFG_DIR}/Rumble.qry
-
-		TITLES=("${(f)$(pup --charset utf8 '.thumbnail__title attr{title}' <<< ${PG})}")
-		LINKS=("${(f)$(pup --charset utf8 '.title__link attr{href}' <<< ${PG})}")
-		AGES=("${(f)$(pup --charset utf8 '.videostream__time text{}' <<< ${PG} | strip_space)}")
-		DURATIONS=("${(f)$(pup --charset utf8 '.videostream__badge text{}' <<< ${PG} | strip_space | grep -E '[0-9].*')}")
+		_RUMBLE_PAGE=$(wget -q -O - ${QRY})
 	elif [[ ${QRY_TYPE} == 'general' ]];then
 		msg_box -c "Requesting <c><I>general<N> search..."
 		GEN_SEARCH=$(sed 's/ /%20/g' <<<${_QUERY_OPTS[QKEY]})
-
 		QRY="https://rumble.com/search/all?q=${GEN_SEARCH}&sort=date&section=sort"
-
-		PG=$(wget -q -O - ${QRY})
-		wget -q -O - ${QRY} > ${_CFG_DIR}/Rumble.qry
-
-		AUTHORS=("${(f)$(pup --charset utf8 '.ellipsis-1 text{}' <<< ${PG} | grep -vi 'verified')}")
-		TITLES=("${(f)$(pup --charset utf8 '.video-item--title text{}' <<< ${PG} | strip_space)}")
-		LINKS=("${(f)$(pup --charset utf8 '.video-item--a attr{href}' <<< ${PG})}")
-		AGES=("${(f)$(pup --charset utf8 '.video-item--time text{}' <<< ${PG} | strip_space)}")
-		DURATIONS=("${(f)$(pup --charset utf8 '.video-item--duration attr{data-value}' <<< ${PG})}")
+		_RUMBLE_PAGE=$(wget -q -O - ${QRY})
 	elif [[ ${QRY_TYPE} == 'user' ]];then
 		msg_box -c "Requesting <c><I>livestream user<N> search..."
-		GEN_SEARCH=$(sed 's/ /%20/g' <<<${_QUERY_OPTS[QKEY]})
-
 		QRY="https://rumble.com/user/${_QUERY_OPTS[QKEY]}/livestreams"
-
-		PG=$(wget -q -O - ${QRY})
-		wget -q -O - ${QRY} > ${_CFG_DIR}/Rumble.qry
-
-		TITLES=("${(f)$(pup --charset utf8 '.thumbnail__title attr{title}' <<< ${PG})}")
-		LINKS=("${(f)$(pup --charset utf8 '.title__link attr{href}' <<< ${PG})}")
-		AGES=("${(f)$(pup --charset utf8 '.videostream__time text{}' <<< ${PG} | strip_space)}")
-		DURATIONS=("${(f)$(pup --charset utf8 '.videostream__badge text{}' <<< ${PG} | strip_space | grep -E '[0-9].*')}")
+		_RUMBLE_PAGE=$(wget -q -O - ${QRY})
 	fi
 
-	# Normalize tables
-	NDX=0
-	for L in ${(a)DURATIONS};do
-		((NDX++))
-		if [[ ! ${L} =~ ':' ]] && NDX_OUT+=${NDX} && continue # Missing colon indicates a live broadcast - eliminate
-		TMP+="${L}"
-	done
-	DURATIONS=(${TMP})
-	TMP=()
-
-	NDX=0
-	for L in ${(a)TITLES};do
-		((NDX++))
-		[[ ${NDX_OUT[(i)${NDX}]} -le ${#NDX_OUT} ]] && continue
-		TITLE=$(recode UTF8..ISO-8859-15 <<<${L:gs/|/#/} 2>/dev/null) # Convert UTF-8
-		TITLE=$(html2text -width ${_MAX_COLS} -ascii <<<${TITLE} 2>/dev/null) # Convert any HTML 
-		TMP+="${TITLE}"
-	done
-	TITLES=(${TMP})
-	TMP=()
-
-	NDX=0
-	for L in ${(a)LINKS};do
-		((NDX++))
-		[[ ${NDX_OUT[(i)${NDX}]} -le ${#NDX_OUT} ]] && continue
-		TMP+="${L}"
-	done
-	LINKS=(${TMP})
-	TMP=()
-
-	# Marshall data
-	NDX=0
-	if [[ ${QRY_TYPE} == 'general' ]];then
-		for L in ${TITLES};do
-			((NDX++))
-			TMP+="${AUTHORS[${NDX}]}|${TITLES[${NDX}]}|${AGES[${NDX}]}|${LINKS[${NDX}]}|${DURATIONS[${NDX}]}"
-		done
-	else
-		for L in ${TITLES};do
-			((NDX++))
-			TMP+="${(C)g_QUERY_KEY}|${TITLES[${NDX}]}|${AGES[${NDX}]}|${LINKS[${NDX}]}|${DURATIONS[${NDX}]}"
-		done
-	fi
-
-	# Return failed search status
-	if ! arr_is_populated "${TMP}";then
-		return 1
-	fi
-
-	_LOCAL_LIST=()
-
-	# Build video listing
-	for L in ${TMP};do
-		AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${L})
-		AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${L})
-		TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${L})
-		URL=$(cut -d'|' -f${FIELD_MAP[url]} <<<${L}); URL="https://rumble.com${URL}"
-		TIME=$(cut -d'|' -f${FIELD_MAP[time]} <<<${L})
-		AGETIME=$(cut -d'|' -f${FIELD_MAP[agetime]} <<<${L});	AGETIME="(${AGETIME:s/|/ /})"
-
-		_LOCAL_LIST+="${AGE}|${AUTHOR}|${TITLE}|${URL}|${TIME}|${AGETIME}"
-	done
-
-	TMP=()
-	TITLES=()
-	LINKS=()
-	AGES=()
-	DURATIONS=()
-
-	return 0
+	[[ -n ${GEN_SEARCH} ]] && GEN_SEARCH='g'
+	parse_rumble ${GEN_SEARCH}
+	[[ ${?} -ne 0 ]] && return 1 || return 0
 }
 
 query_youtube () {
 	local -a WORK_LIST=()
-	local -A FIELD_MAP=("age" 1 "author" 2 "title" 3 "url" 4 "time" 5 "agetime" "1,5")
+	local -A YOUTUBE_MAP=("age" 1 "author" 2 "title" 3 "url" 4 "time" 5 "agetime" "1,5")
 	local AGE AUTHOR TITLE URL TIME AGETIME
 	local DATA=false
 	local HIT=false
@@ -1360,17 +1329,17 @@ query_youtube () {
 	fi
 
 	for F in ${_LOCAL_LIST};do
-		AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${F})
-		AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${F})
-		TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${F}); TITLE=$(clean_title ${TITLE})
+		AGE=$(cut -d'|' -f${YOUTUBE_MAP[age]} <<<${F})
+		AUTHOR=$(cut -d'|' -f${YOUTUBE_MAP[author]} <<<${F})
+		TITLE=$(cut -d'|' -f${YOUTUBE_MAP[title]} <<<${F}); TITLE=$(clean_title ${TITLE})
 		if [[ ${AUTHOR} == 'blancolirio' ]];then # Weird problem workaraound - spanish titles on blancolirio
 			if perl -wln -e "if (/\b.*[ae]ntes\b|\bll.*\b|\bel\b|\bya\b|\by\b|\bla\b|\bal\b|\bde\b|\bdel\b|\bque\b|\bpara\b|\bpor\b/) { exit 0 } else { exit 1 }" <<<${TITLE:l};then
 				TITLE=$(echo ${TITLE} | trans -brief -no-pager -no-ansi -no-theme es:en 2>/dev/null)
 			fi
 		fi
-		URL=$(cut -d'|' -f${FIELD_MAP[url]} <<<${F})
-		TIME=$(cut -d'|' -f${FIELD_MAP[time]} <<<${F})
-		AGETIME=$(cut -d'|' -f${FIELD_MAP[agetime]} <<<${F});	AGETIME="(${AGETIME:s/|/ /})"
+		URL=$(cut -d'|' -f${YOUTUBE_MAP[url]} <<<${F})
+		TIME=$(cut -d'|' -f${YOUTUBE_MAP[time]} <<<${F})
+		AGETIME=$(cut -d'|' -f${YOUTUBE_MAP[agetime]} <<<${F});	AGETIME="(${AGETIME:s/|/ /})"
 		WORK_LIST+="${AGE}|${AUTHOR}|${TITLE}|${URL}|${TIME}|${AGETIME}"
 	done
 
@@ -1459,11 +1428,19 @@ set_query_opts () {
 	_QUERY_OPTS[EOPT]=${ENG_OPT:l}
 }
 
-strip_space () {
+strip_unwanted () {
 	local LINE
 
-	while read LINE;do
-		tr -d '\011' | tr -s '\012' | sed '/^$/d' <<< ${LINE}
+	while read -r LINE;do
+		[[ -z ${LINE} ]] && continue
+		[[ ${LINE} =~ '^[Vv]erified$' ]] && continue
+		[[ ${LINE} =~ '^LIVE$' ]] && continue
+		LINE=$(tr -d '\011' <<< ${LINE})
+		LINE=$(tr -d '\012' <<< ${LINE})
+		LINE=$(sed 's/|/#/g' <<< ${LINE})
+		LINE=$(iconv -c -f UTF-8 -t ASCII <<<${LINE} 2>/dev/null) # Convert UTF-8
+		LINE=$(html2text -width 500 -ascii <<<${LINE} 2>/dev/null) # Convert any HTML 
+		str_trim <<< ${LINE}
 	done
 }
 
@@ -1702,8 +1679,6 @@ else # Args passed
 		_QUERY_OPTS[EOPT]=${QTYPE}
 	fi
 	query_${_QUERY_OPTS[ENGINE]}
-	# TODO: During testing a youtube query of 'maga' hangs during list display - unknown cause
-	# TODO: Needs more testing with command line args to youtube
 	if [[ ${?} -eq 0 ]];then # Inspect query status
 		download_select ${_QUERY_OPTS[QKEY]}
 		[[ ${g_CMDLINE_ARGS} == 'true' ]] && fav_add
