09-05-2025-09:26:33

diff --git a/ZSH_LIB_UTILS/yts b/ZSH_LIB_UTILS/yts
--- a/ZSH_LIB_UTILS/yts
+++ b/ZSH_LIB_UTILS/yts
@@ -82,6 +82,7 @@ _YTS_URL_LOG=/tmp/yts.url.log
 g_DISPLAY_KEY=''
 g_IND_FLIP=false
 g_LAST_CODE_UPD=?
+g_LAST_SPEED=0
 g_LTYPE=y
 g_MASK_NDX=1
 g_PID=?
@@ -134,10 +135,11 @@ action_do () {
 	local RC1=0
 	local RC2=0
 	local SCAN_LIMIT=0
+	local SPEED=0
 	local TITLE=''
 	local URL=''
 	local WAIT=0
-	local L M S 
+	local L M S X
 
 	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
 
@@ -340,7 +342,9 @@ action_do () {
 			LINE_COLOR=''
 			if [[ -n ${ETA} && ${ETA_COMPLETE} == 'false' ]];then
 				ERROR_CNT=0 
-				download_indicator ${ETA}
+				[[ ${g_QRY_ENGINE} == 'youtube' ]] && X=6 || X=7
+				SPEED=$(tr -s '[:space:]' <<<${ETA:l} | cut -d' ' -f${X} | cut -d'/' -f1)
+				download_indicator ${SPEED}
 				case ${ETA:l} in
 					*100*%*) LINE_COLOR='<B><g>';ETA_COMPLETE=true;; # Stop parsing ETA
 					*mib/s*) LINE_COLOR='<w>';;
@@ -516,7 +520,7 @@ dashed_line () {
 }
 
 download_indicator () {
-	local LINE=${@}
+	local SPEED=${1}
 	local L_OBJ="\\u23FA"
 	local M_OBJ="\\u25CF"
 	local R_OBJ="\\u2B24"
@@ -531,12 +535,44 @@ download_indicator () {
 	local IND_X=$(( _ALERT_COORDS[X] + 1 ))
 	local IND_Y=$(( _ALERT_COORDS[Y] + 7 ))
 	local OBJ_COLOR="${BOLD}${GREEN_FG}"
+	local SP_TYPE=''
+	local LSP_TYPE=''
+	local LSPEED=0
+	local SP_DIR=I
 
-	case ${LINE:l} in
-		*mib*) BORDER_COLOR="${BOLD}${MAGENTA_FG}";;
-		*kib*) BORDER_COLOR="${BOLD}${RED_FG}";;
-	esac
-	
+	[[ -n ${SPEED} ]] && SPEED=${SPEED[1,-4]} || SPEED=0
+	[[ -n ${SPEED} && ${SPEED} =~ 'mib' ]] && SP_TYPE='M' || SP_TYPE='K'
+
+	[[ -n ${g_LAST_SPEED} ]] && LSPEED=${g_LAST_SPEED[1,-4]} || LSPEED=0
+	[[ -n ${g_LAST_SPEED} && ${g_LAST_SPEED} =~ 'mib' ]] && LSP_TYPE='M' || LSP_TYPE='K'
+
+	#echo "SPEED:${SPEED}, LSPEED:${LSPEED}, SP_TYPE:${SP_TYPE}, LSP_TYPE:${LSP_TYPE}" >>x
+
+	if [[ ${SPEED} -gt ${LSPEED} ]];then 
+		OBJ_COLOR="${BOLD}${GREEN_FG}"
+		SP_DIR=I # Increasing
+	elif [[ ${SPEED} -lt ${LSPEED} ]];then 
+		OBJ_COLOR="${BOLD}${YELLOW_FG}"
+		SP_DIR=D # Decreasing
+	else
+		OBJ_COLOR="${BOLD}${WHITE_FG}"
+		SP_DIR=I # Stable
+	fi
+
+	if [[ ${SP_TYPE} == 'M' && LSP_TYPE == 'K' ]];then 
+		OBJ_COLOR="${BOLD}${GREEN_FG}"
+		SP_DIR=I # Increasing
+	elif [[ ${SP_TYPE} == 'K' && LSP_TYPE == 'M' ]];then 
+		OBJ_COLOR="${BOLD}${YELLOW_FG}"
+		SP_DIR=D # Decreasing
+	fi
+
+	if [[ ${SP_DIR} == 'I' ]];then 
+		BORDER_COLOR="${BOLD}${MAGENTA_FG}"
+	elif [[ ${SP_DIR} == 'D' ]];then 
+		BORDER_COLOR="${BOLD}${RED_FG}"
+	fi
+
 	OBJS=(${(kv)OBJS_1}) # Init
 
 	if [[ ${g_IND_FLIP} == 'true' ]];then
@@ -557,6 +593,8 @@ download_indicator () {
 	[[ ${g_MASK_NDX} -gt 3 ]] && g_MASK_NDX=1
 
  	tcup ${IND_X} ${IND_Y} && echo -n "${MASK}" && sleep ${DELAY}
+
+	g_LAST_SPEED=${SPEED}
 }
 
 download_select () {
@@ -881,17 +919,19 @@ get_field () {
 		[[ ${STR:l} =~ 'live' ]] && STR=$(sed -E 's/(.*ago)( live)(.*)/\1)/I' <<<${STR})
 	fi
 
-	if [[ ${FIELD} == 'author' ]];then
-		if [[ ${g_SEARCH_TYPE} == 'general' ]];then
- 			TSTR=${(C)STR}
-		else
-			[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}: Author:${STR} swapped with g_DISPLAY_KEY:${g_DISPLAY_KEY}"
-			TSTR=${g_DISPLAY_KEY:gs/_/ /}
-		fi
-		STR=${TSTR:=${STR}}
-	fi
+#	if [[ ${FIELD} == 'author' ]];then
+#		if [[ ${g_SEARCH_TYPE} == 'general' ]];then
+# 			TSTR=${(C)STR}
+#		else
+#			[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}: Author:${STR} swapped with g_DISPLAY_KEY:${g_DISPLAY_KEY}"
+#			TSTR=${g_DISPLAY_KEY:gs/_/ /}
+#		fi
+#		STR=${TSTR:=${STR}}
+#	fi
 
-	#logit ${_YTS_DBG_LOG} "${0}: FIELD:${FIELD} STR:${STR}"
+	if [[ ${FIELD} == 'author' ]];then
+		STR=${g_DISPLAY_KEY:gs/_/ /}
+	fi
 
 	if [[ -n ${_FIELD_LEN[${FIELD}]} ]];then
 		echo -n ${STR[1,${_FIELD_LEN[${FIELD}]}]}
@@ -1434,77 +1474,77 @@ query_youtube () {
 	if [[ ${g_STRICT} == 'true' ]];then # Strict requested
 		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}STRICT FILTER ACTIVE${RESET}"
 		g_PROXY_CMD="node ${_JS_SCRIPT} -s ${(qqq)g_QUERY_KEY}"
-	else
-		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}STRICT FILTER INACTIVE${RESET}"
-		g_PROXY_CMD="node ${_JS_SCRIPT} -a recent ${(qqq)g_QUERY_KEY}"
-	fi
-
-	if [[ ${_DEBUG} -ge ${_LOW_DBG} ]];then
-		dbg "${0}:${LINENO} ${CYAN_FG}g_QUERY_KEY${RESET}:${g_QUERY_KEY}, {CYAN_FG}g_PROXY_CMD${RESET}:${g_PROXY_CMD}"
-	fi
-
-	logit ${_YTS_DBG_LOG} "${0}:g_QUERY_KEY:${g_QUERY_KEY}, g_PROXY_CMD:${g_PROXY_CMD}"
-
-	_LOCAL_LIST=()
-
-	g_SEARCH_TYPE='general'
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}GENERAL SEARCH${RESET}"
-
-	NDX=0
-	while read LINE;do
-		[[ ${LINE:l} =~ 'matched' ]] && DATA=true && continue
-
-		[[ ${LINE:l} =~ 'usage' && ${DATA} != 'true' ]] && exit_leave
-		[[ ${LINE:l} =~ 'error' && ${DATA} != 'true' ]] && exit_leave $(err_msg_exit E "${PROXY_CMD} returned an error")
-
-		((NDX++))
-		[[ ${LINE:l} =~ 'rejected' ]] && _REJECTS[${NDX}]=true || _REJECTS[${NDX}]=false
-
-		STR=$(str_to_ascii <<<${LINE}) # Scrub non ascii
-		STR=${STR:s/Streamed //}
-
-		if [[ ${g_STRICT} == 'false' ]];then # Apply filtering to non strict results
-			HIT=false
-			AUTHOR=$(cut -d'|' -f2 <<<${LINE}) && AUTHOR=$(str_to_ascii ${AUTHOR})
-			TITLE=$(cut -d'|' -f3 <<<${LINE}) && TITLE=$(str_to_ascii ${TITLE})
-			[[ ${TITLE:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:gs/ //:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
-			if [[ ${_DEBUG} -ge ${_MID_DBG} ]];then
-				dbg "${0}:${LINENO} NON STRICT FILTERING, AUTHOR:${AUTHOR}, g_DISPLAY_KEY:${g_DISPLAY_KEY}, g_QUERY_KEY:${g_QUERY_KEY}, HIT:${HIT}"
-			fi
-			[[ ${HIT} == 'false' ]] && continue
-		fi
-		 
-		[[ ${_REJECTS[${NDX}]} == 'false' && ${DATA} == 'true' ]] && _LOCAL_LIST+=${STR}
-	done< <(eval ${g_PROXY_CMD})
-
-	[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="$(total_rejects ${NDX})" || g_STRICT_MSG=''
-
-	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
-	[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST content:\n $(for L in ${_LOCAL_LIST};do echo ${L};done)"
-
-	[[ ${_SMCUP} == 'false' ]] && do_smcup
-
-	# Search failed
-	if ! arr_is_populated "${_LOCAL_LIST}";then
-		g_PROXY_CMD=$(str_trim ${(Q)g_PROXY_CMD})
-		if [[ ${g_STRICT} == 'true' ]];then
-			msg_box -H2 -p -PK "<r>Query returned no rows<N>|<I>Strict filter is active<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
 		else
-			msg_box -H2 -p -PK "<r>Query returned no rows<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
+			[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}STRICT FILTER INACTIVE${RESET}"
+			g_PROXY_CMD="node ${_JS_SCRIPT} -a recent ${(qqq)g_QUERY_KEY}"
 		fi
-		return 1
-	fi
 
-	for F in ${_LOCAL_LIST};do
-		AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${F})
-		AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${F})
-		TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${F}); TITLE=$(clean_title ${TITLE})
-		if [[ ${AUTHOR} == 'blancolirio' ]];then # Weird problem workaraound - spanish titles on blancolirio
-			if perl -wln -e "if (/\b.*[ae]ntes\b|\bll.*\b|\bel\b|\bya\b|\by\b|\bla\b|\bal\b|\bde\b|\bdel\b|\bque\b/) { exit 0 } else { exit 1 }" <<<${TITLE:l};then
-				TITLE=$(echo ${TITLE} | trans -brief -no-pager -no-ansi -no-theme es:en)
+		if [[ ${_DEBUG} -ge ${_LOW_DBG} ]];then
+			dbg "${0}:${LINENO} ${CYAN_FG}g_QUERY_KEY${RESET}:${g_QUERY_KEY}, {CYAN_FG}g_PROXY_CMD${RESET}:${g_PROXY_CMD}"
+		fi
+
+		logit ${_YTS_DBG_LOG} "${0}:g_QUERY_KEY:${g_QUERY_KEY}, g_PROXY_CMD:${g_PROXY_CMD}"
+
+		_LOCAL_LIST=()
+
+		g_SEARCH_TYPE='general'
+		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} ${CYAN_FG}GENERAL SEARCH${RESET}"
+
+		NDX=0
+		while read LINE;do
+			[[ ${LINE:l} =~ 'matched' ]] && DATA=true && continue
+
+			[[ ${LINE:l} =~ 'usage' && ${DATA} != 'true' ]] && exit_leave
+			[[ ${LINE:l} =~ 'error' && ${DATA} != 'true' ]] && exit_leave $(err_msg_exit E "${PROXY_CMD} returned an error")
+
+			((NDX++))
+			[[ ${LINE:l} =~ 'rejected' ]] && _REJECTS[${NDX}]=true || _REJECTS[${NDX}]=false
+
+			STR=$(str_to_ascii <<<${LINE}) # Scrub non ascii
+			STR=${STR:s/Streamed //}
+
+			if [[ ${g_STRICT} == 'false' ]];then # Apply filtering to non strict results
+				HIT=false
+				AUTHOR=$(cut -d'|' -f2 <<<${LINE}) && AUTHOR=$(str_to_ascii ${AUTHOR})
+				TITLE=$(cut -d'|' -f3 <<<${LINE}) && TITLE=$(str_to_ascii ${TITLE})
+				[[ ${TITLE:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
+				[[ ${AUTHOR:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
+				[[ ${AUTHOR:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
+				[[ ${AUTHOR:gs/ //:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
+				if [[ ${_DEBUG} -ge ${_MID_DBG} ]];then
+					dbg "${0}:${LINENO} NON STRICT FILTERING, AUTHOR:${AUTHOR}, g_DISPLAY_KEY:${g_DISPLAY_KEY}, g_QUERY_KEY:${g_QUERY_KEY}, HIT:${HIT}"
+				fi
+				[[ ${HIT} == 'false' ]] && continue
+			fi
+			 
+			[[ ${_REJECTS[${NDX}]} == 'false' && ${DATA} == 'true' ]] && _LOCAL_LIST+=${STR}
+		done< <(eval ${g_PROXY_CMD})
+
+		[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="$(total_rejects ${NDX})" || g_STRICT_MSG=''
+
+		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
+		[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST content:\n $(for L in ${_LOCAL_LIST};do echo ${L};done)"
+
+		[[ ${_SMCUP} == 'false' ]] && do_smcup
+
+		# Search failed
+		if ! arr_is_populated "${_LOCAL_LIST}";then
+			g_PROXY_CMD=$(str_trim ${(Q)g_PROXY_CMD})
+			if [[ ${g_STRICT} == 'true' ]];then
+				msg_box -H2 -p -PK "<r>Query returned no rows<N>|<I>Strict filter is active<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
+			else
+				msg_box -H2 -p -PK "<r>Query returned no rows<N>|<w>g_PROXY_CMD<N>:${g_PROXY_CMD}"
+			fi
+			return 1
+		fi
+
+		for F in ${_LOCAL_LIST};do
+			AGE=$(cut -d'|' -f${FIELD_MAP[age]} <<<${F})
+			AUTHOR=$(cut -d'|' -f${FIELD_MAP[author]} <<<${F})
+			TITLE=$(cut -d'|' -f${FIELD_MAP[title]} <<<${F}); TITLE=$(clean_title ${TITLE})
+			if [[ ${AUTHOR} == 'blancolirio' ]];then # Weird problem workaraound - spanish titles on blancolirio
+				if perl -wln -e "if (/\b.*[ae]ntes\b|\bll.*\b|\bel\b|\bya\b|\by\b|\bla\b|\bal\b|\bde\b|\bdel\b|\bque\b/) { exit 0 } else { exit 1 }" <<<${TITLE:l};then
+					TITLE=$(echo ${TITLE} | trans -brief -no-pager -no-ansi -no-theme es:en)
 			fi
 		fi
 		URL=$(cut -d'|' -f${FIELD_MAP[url]} <<<${F})
